import type { MockCategory } from "../api/mock-store/types";

// 36 categories: 8 parent + 28 leaf
export const dbCategories: MockCategory[] = [
  // ── Parent categories ──────────────────────────────────────────────────────
  {
    id: "cat_electronics", name: "Electronics", slug: "electronics", level: 0,
    description: "Smartphones, laptops, tablets, audio gear, cameras & smart home devices.",
    productCount: 300, featured: true,
    tone: "from-blue-500/20 via-indigo-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&h=400&fit=crop&q=80",
    icon: "Cpu",
  },
  {
    id: "cat_fashion", name: "Fashion", slug: "fashion", level: 0,
    description: "Clothing, shoes, bags, jewelry & accessories for every style.",
    productCount: 320, featured: true,
    tone: "from-pink-500/20 via-rose-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&h=400&fit=crop&q=80",
    icon: "Shirt",
  },
  {
    id: "cat_home", name: "Home & Living", slug: "home-living", level: 0,
    description: "Furniture, kitchen appliances, bedding & home decor.",
    productCount: 170, featured: true,
    tone: "from-amber-500/20 via-orange-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop&q=80",
    icon: "Home",
  },
  {
    id: "cat_beauty", name: "Beauty & Personal Care", slug: "beauty", level: 0,
    description: "Skincare, makeup, hair care & fragrance products.",
    productCount: 100, featured: true,
    tone: "from-purple-500/20 via-violet-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=400&fit=crop&q=80",
    icon: "Sparkles",
  },
  {
    id: "cat_sports", name: "Sports & Outdoors", slug: "sports-outdoors", level: 0,
    description: "Fitness equipment, sportswear & outdoor gear.",
    productCount: 40, featured: false,
    tone: "from-green-500/20 via-emerald-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=400&fit=crop&q=80",
    icon: "Dumbbell",
  },
  {
    id: "cat_books", name: "Books & Education", slug: "books-education", level: 0,
    description: "Books, textbooks, stationery & learning supplies.",
    productCount: 0, featured: false,
    tone: "from-teal-500/20 via-cyan-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=400&fit=crop&q=80",
    icon: "BookOpen",
  },
  {
    id: "cat_food", name: "Food & Grocery", slug: "food-grocery", level: 0,
    description: "Snacks, beverages, health foods & everyday grocery items.",
    productCount: 0, featured: false,
    tone: "from-lime-500/20 via-green-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop&q=80",
    icon: "ShoppingBasket",
  },
  {
    id: "cat_gaming", name: "Gaming", slug: "gaming", level: 0,
    description: "Consoles, games, gaming peripherals & accessories.",
    productCount: 30, featured: true,
    tone: "from-red-500/20 via-rose-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=400&fit=crop&q=80",
    icon: "Gamepad2",
  },

  // ── Electronics children ───────────────────────────────────────────────────
  {
    id: "cat_phone", name: "Smartphones", slug: "smartphones", level: 1, parentId: "cat_electronics",
    description: "Latest flagship and mid-range smartphones from top brands.",
    productCount: 80, featured: true,
    tone: "from-blue-500/20 via-indigo-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=400&fit=crop&q=80",
    icon: "Smartphone",
  },
  {
    id: "cat_laptop", name: "Laptops & Computers", slug: "laptops-computers", level: 1, parentId: "cat_electronics",
    description: "Ultrabooks, gaming laptops, workstations & desktop PCs.",
    productCount: 80, featured: true,
    tone: "from-indigo-500/20 via-blue-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=400&fit=crop&q=80",
    icon: "Laptop",
  },
  {
    id: "cat_tablet", name: "Tablets", slug: "tablets", level: 1, parentId: "cat_electronics",
    description: "iPads, Android tablets & e-readers for work and entertainment.",
    productCount: 40, featured: false,
    tone: "from-sky-500/20 via-blue-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1544244015-0321-4036-b8b7-ea7fe32a5b70?w=600&h=400&fit=crop&q=80",
    icon: "Tablet",
  },
  {
    id: "cat_audio", name: "Audio & Headphones", slug: "audio-headphones", level: 1, parentId: "cat_electronics",
    description: "Wireless headphones, earbuds, speakers & home audio systems.",
    productCount: 60, featured: true,
    tone: "from-cyan-500/20 via-sky-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=400&fit=crop&q=80",
    icon: "Headphones",
  },
  {
    id: "cat_camera", name: "Cameras & Photography", slug: "cameras-photography", level: 1, parentId: "cat_electronics",
    description: "DSLR, mirrorless cameras, lenses, action cams & accessories.",
    productCount: 40, featured: false,
    tone: "from-slate-500/20 via-gray-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1606746723-979e3e22e2b5?w=600&h=400&fit=crop&q=80",
    icon: "Camera",
  },
  {
    id: "cat_smarthome", name: "Smart Home", slug: "smart-home", level: 1, parentId: "cat_electronics",
    description: "Smart speakers, lighting, security cameras & home automation.",
    productCount: 40, featured: false,
    tone: "from-violet-500/20 via-purple-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop&q=80",
    icon: "Wifi",
  },

  // ── Fashion children ───────────────────────────────────────────────────────
  {
    id: "cat_mens", name: "Men's Clothing", slug: "mens-clothing", level: 1, parentId: "cat_fashion",
    description: "T-shirts, jeans, jackets, suits & sportswear for men.",
    productCount: 80, featured: true,
    tone: "from-blue-500/20 via-slate-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=400&fit=crop&q=80",
    icon: "User",
  },
  {
    id: "cat_womens", name: "Women's Clothing", slug: "womens-clothing", level: 1, parentId: "cat_fashion",
    description: "Dresses, tops, jeans, skirts & outerwear for women.",
    productCount: 80, featured: true,
    tone: "from-pink-500/20 via-rose-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&h=400&fit=crop&q=80",
    icon: "User",
  },
  {
    id: "cat_shoes", name: "Shoes & Footwear", slug: "shoes-footwear", level: 1, parentId: "cat_fashion",
    description: "Sneakers, running shoes, boots, sandals & formal footwear.",
    productCount: 80, featured: true,
    tone: "from-orange-500/20 via-amber-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=400&fit=crop&q=80",
    icon: "Footprints",
  },
  {
    id: "cat_bags", name: "Bags & Accessories", slug: "bags-accessories", level: 1, parentId: "cat_fashion",
    description: "Handbags, backpacks, wallets, belts & travel bags.",
    productCount: 50, featured: false,
    tone: "from-yellow-500/20 via-amber-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1548036161-58be4d08b498?w=600&h=400&fit=crop&q=80",
    icon: "ShoppingBag",
  },
  {
    id: "cat_jewelry", name: "Jewelry & Watches", slug: "jewelry-watches", level: 1, parentId: "cat_fashion",
    description: "Necklaces, rings, bracelets, earrings & luxury watches.",
    productCount: 30, featured: false,
    tone: "from-amber-500/20 via-yellow-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&h=400&fit=crop&q=80",
    icon: "Gem",
  },

  // ── Home children ──────────────────────────────────────────────────────────
  {
    id: "cat_furniture", name: "Furniture", slug: "furniture", level: 1, parentId: "cat_home",
    description: "Sofas, beds, dining tables, office desks & storage solutions.",
    productCount: 60, featured: true,
    tone: "from-amber-500/20 via-orange-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=400&fit=crop&q=80",
    icon: "Sofa",
  },
  {
    id: "cat_kitchen", name: "Kitchen & Dining", slug: "kitchen-dining", level: 1, parentId: "cat_home",
    description: "Stand mixers, coffee makers, cookware & kitchen gadgets.",
    productCount: 50, featured: true,
    tone: "from-orange-500/20 via-red-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&h=400&fit=crop&q=80",
    icon: "UtensilsCrossed",
  },
  {
    id: "cat_bedding", name: "Bedding & Bath", slug: "bedding-bath", level: 1, parentId: "cat_home",
    description: "Mattresses, pillows, duvet covers, sheets & bath towels.",
    productCount: 30, featured: false,
    tone: "from-sky-500/20 via-blue-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&h=400&fit=crop&q=80",
    icon: "BedDouble",
  },
  {
    id: "cat_decor", name: "Home Decor", slug: "home-decor", level: 1, parentId: "cat_home",
    description: "Vases, lighting, wall art, rugs, throws & decorative objects.",
    productCount: 30, featured: false,
    tone: "from-emerald-500/20 via-teal-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&h=400&fit=crop&q=80",
    icon: "Lamp",
  },

  // ── Beauty children ────────────────────────────────────────────────────────
  {
    id: "cat_skincare", name: "Skincare", slug: "skincare", level: 1, parentId: "cat_beauty",
    description: "Serums, moisturizers, cleansers, SPF & anti-aging treatments.",
    productCount: 50, featured: true,
    tone: "from-rose-500/20 via-pink-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=400&fit=crop&q=80",
    icon: "Droplets",
  },
  {
    id: "cat_makeup", name: "Makeup & Cosmetics", slug: "makeup-cosmetics", level: 1, parentId: "cat_beauty",
    description: "Foundation, lipstick, eyeshadow palettes, mascara & setting spray.",
    productCount: 50, featured: true,
    tone: "from-fuchsia-500/20 via-purple-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&h=400&fit=crop&q=80",
    icon: "Paintbrush",
  },
  {
    id: "cat_haircare", name: "Hair Care", slug: "hair-care", level: 1, parentId: "cat_beauty",
    description: "Shampoo, conditioner, hair masks, dryers & styling tools.",
    productCount: 0, featured: false,
    tone: "from-violet-500/20 via-purple-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600&h=400&fit=crop&q=80",
    icon: "Wind",
  },
  {
    id: "cat_fragrance", name: "Fragrance", slug: "fragrance", level: 1, parentId: "cat_beauty",
    description: "Eau de parfum, cologne, body mists & gift sets.",
    productCount: 0, featured: false,
    tone: "from-indigo-500/20 via-violet-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1557170334-a9632e77c6e4?w=600&h=400&fit=crop&q=80",
    icon: "Wind",
  },

  // ── Sports children ────────────────────────────────────────────────────────
  {
    id: "cat_fitness", name: "Fitness & Exercise", slug: "fitness-exercise", level: 1, parentId: "cat_sports",
    description: "Dumbbells, yoga mats, GPS watches, resistance bands & gym gear.",
    productCount: 40, featured: true,
    tone: "from-green-500/20 via-emerald-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=400&fit=crop&q=80",
    icon: "Dumbbell",
  },
  {
    id: "cat_outdoor", name: "Outdoor & Adventure", slug: "outdoor-adventure", level: 1, parentId: "cat_sports",
    description: "Hiking boots, tents, climbing gear & outdoor apparel.",
    productCount: 0, featured: false,
    tone: "from-lime-500/20 via-green-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop&q=80",
    icon: "TreePine",
  },
  {
    id: "cat_team", name: "Team Sports", slug: "team-sports", level: 1, parentId: "cat_sports",
    description: "Football, basketball, tennis, cycling & team sport gear.",
    productCount: 0, featured: false,
    tone: "from-teal-500/20 via-cyan-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=600&h=400&fit=crop&q=80",
    icon: "Trophy",
  },

  // ── Books children ─────────────────────────────────────────────────────────
  {
    id: "cat_books_item", name: "Books", slug: "books", level: 1, parentId: "cat_books",
    description: "Bestselling fiction, non-fiction, textbooks & children's books.",
    productCount: 0, featured: false,
    tone: "from-teal-500/20 via-cyan-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=400&fit=crop&q=80",
    icon: "Book",
  },
  {
    id: "cat_stationery", name: "Stationery", slug: "stationery", level: 1, parentId: "cat_books",
    description: "Notebooks, pens, planners, art supplies & office stationery.",
    productCount: 0, featured: false,
    tone: "from-cyan-500/20 via-teal-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1553545204-4f7d339aa06a?w=600&h=400&fit=crop&q=80",
    icon: "PenLine",
  },

  // ── Food children ──────────────────────────────────────────────────────────
  {
    id: "cat_snacks", name: "Snacks & Beverages", slug: "snacks-beverages", level: 1, parentId: "cat_food",
    description: "Chips, chocolate, coffee, tea & soft drinks.",
    productCount: 0, featured: false,
    tone: "from-lime-500/20 via-green-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=400&fit=crop&q=80",
    icon: "Cookie",
  },
  {
    id: "cat_health_food", name: "Health Foods", slug: "health-foods", level: 1, parentId: "cat_food",
    description: "Protein supplements, vitamins, organic foods & superfoods.",
    productCount: 0, featured: false,
    tone: "from-green-500/20 via-lime-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&h=400&fit=crop&q=80",
    icon: "Apple",
  },

  // ── Gaming children ────────────────────────────────────────────────────────
  {
    id: "cat_console", name: "Consoles & Games", slug: "consoles-games", level: 1, parentId: "cat_gaming",
    description: "PlayStation, Xbox, Nintendo Switch consoles & game titles.",
    productCount: 15, featured: true,
    tone: "from-red-500/20 via-orange-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=400&fit=crop&q=80",
    icon: "Gamepad2",
  },
  {
    id: "cat_pc_gaming", name: "PC Gaming", slug: "pc-gaming", level: 1, parentId: "cat_gaming",
    description: "Gaming keyboards, mice, headsets, chairs & PC accessories.",
    productCount: 15, featured: true,
    tone: "from-orange-500/20 via-red-500/10 to-transparent",
    image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=400&fit=crop&q=80",
    icon: "Monitor",
  },
];
