import type { MockProduct } from "../api/mock-store/types";

// ── CDN image pools per category (Unsplash) ──────────────────────────────────
const IMG = {
  phones: [
    "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1556656793-08b88f082c5f?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=800&q=80&auto=format&fit=crop",
  ],
  laptops: [
    "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1484788984921-03950022c9ef?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1541807084-5c52e6a279dd?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80&auto=format&fit=crop",
  ],
  tablets: [
    "https://images.unsplash.com/photo-1544244015-0321-4036-b8b7-ea7fe32a5b70?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1561154464-02ce0a2f0816?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1589739900266-43b2843f4c12?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1486401899868-0e435ed85128?w=800&q=80&auto=format&fit=crop",
  ],
  audio: [
    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1578353022142-09264fd64295?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1545127398-14699f92334b?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1563302111-eab4b145e6c9?w=800&q=80&auto=format&fit=crop",
  ],
  cameras: [
    "https://images.unsplash.com/photo-1606746723-979e3e22e2b5?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1520390138845-fd2d229dd553?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1581591524425-c7e0978865fc?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1608138404239-d2f9b5c90ee3?w=800&q=80&auto=format&fit=crop",
  ],
  smarthome: [
    "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1573920111631-ef10a981698a?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1592323360925-d48adeff4dd4?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1544894079-e81a9eb5bd89?w=800&q=80&auto=format&fit=crop",
  ],
  mens: [
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1479936343596-bb4c4b4dd4e3?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=800&q=80&auto=format&fit=crop",
  ],
  womens: [
    "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1485231183945-fffde7af8573?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1631730220-a97bec2f1474?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80&auto=format&fit=crop",
  ],
  shoes: [
    "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80&auto=format&fit=crop",
  ],
  bags: [
    "https://images.unsplash.com/photo-1548036161-58be4d08b498?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&q=80&auto=format&fit=crop",
  ],
  jewelry: [
    "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1609519777893-a83c4360ae44?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1546452738-1bef55e65bae?w=800&q=80&auto=format&fit=crop",
  ],
  furniture: [
    "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1556909190-8cbed7c53009?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1586023492125-27b2c045efd3?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80&auto=format&fit=crop",
  ],
  kitchen: [
    "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1574269909766-4ae785b2f2b1?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1593443320739-77f74939d0da?w=800&q=80&auto=format&fit=crop",
  ],
  bedding: [
    "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1586023492125-27b2c045efd3?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80&auto=format&fit=crop",
  ],
  decor: [
    "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
  ],
  skincare: [
    "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1515688755929-09b55d8fd27e?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&q=80&auto=format&fit=crop",
  ],
  makeup: [
    "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1583241475880-083f84372725?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1621072156002-e2fccdc0b176?w=800&q=80&auto=format&fit=crop",
  ],
  fitness: [
    "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1534258936925-c58bed479fcb?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800&q=80&auto=format&fit=crop",
  ],
  gaming: [
    "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1542751110-a4eb0bb99d59?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&q=80&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80&auto=format&fit=crop",
  ],
} as const;

// ── Deterministic seeded random ──────────────────────────────────────────────
function dr(seed: number, min: number, max: number): number {
  const x = Math.sin(seed * 9301 + 49297) * 233280;
  return min + Math.floor((x - Math.floor(x)) * (max - min + 1));
}

// ── Product counter ──────────────────────────────────────────────────────────
let _pid = 0;

// ── Core generator ──────────────────────────────────────────────────────────
interface Def {
  name: string;
  brand: string;
  brandId: string;
  categoryId: string;
  categorySlug: string;
  categoryName: string;
  priceMin: number;
  priceMax: number;
  images: readonly string[];
  tags: string[];
  description: string;
  color?: string;
}

function gen(def: Def): MockProduct {
  const idx = ++_pid;
  const s = idx * 7919;
  const pRange = (def.priceMax - def.priceMin) * 100;
  const price = Math.round((def.priceMin + dr(s, 0, pRange) / 100) * 100) / 100;
  const imgLen = def.images.length;
  const i0 = dr(s + 4, 0, imgLen - 1);
  const imgs = [
    def.images[i0],
    def.images[(i0 + 1) % imgLen],
    def.images[(i0 + 2) % imgLen],
  ];
  const slug = def.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const hasDiscount = dr(s + 1, 0, 9) > 5;
  const statusRoll = dr(s + 3, 0, 9);

  return {
    id: `prod_${String(idx).padStart(4, "0")}`,
    name: def.name,
    slug,
    sku: `${def.brandId.replace("brand_", "").slice(0, 4).toUpperCase()}-${idx}`,
    price,
    currency: "USD",
    thumbnail: imgs[0],
    images: imgs,
    description: def.description,
    brand: def.brand,
    brandId: def.brandId,
    categoryId: def.categoryId,
    categorySlug: def.categorySlug,
    categoryName: def.categoryName,
    compareAtPrice: hasDiscount ? Math.round(price * (1 + dr(s + 5, 10, 30) / 100) * 100) / 100 : undefined,
    cost: Math.round(price * 0.55 * 100) / 100,
    rating: dr(s + 6, 35, 50) / 10,
    reviewCount: dr(s + 7, 5, 2000),
    stock: dr(s + 2, 0, 300),
    status: statusRoll < 7 ? "active" : statusRoll < 9 ? "draft" : "archived",
    tags: def.tags,
    color: def.color,
    featured: dr(s + 8, 0, 19) === 0,
    releaseDate: `202${dr(s + 9, 1, 4)}-${String(dr(s + 10, 1, 12)).padStart(2, "0")}-01`,
  };
}

// ── Series helper: one product per model name ────────────────────────────────
function s(
  brand: string, brandId: string,
  catId: string, catSlug: string, catName: string,
  pMin: number, pMax: number,
  imgs: readonly string[], tags: string[], desc: string,
  models: string[], color?: string,
): MockProduct[] {
  return models.map((name) => gen({ name, brand, brandId, categoryId: catId, categorySlug: catSlug, categoryName: catName, priceMin: pMin, priceMax: pMax, images: imgs, tags, description: desc, color }));
}

// ── PRODUCT CATALOG (1 000 products) ────────────────────────────────────────
export const mockProducts: MockProduct[] = [

  // ════════════════════════════════════════════════════════════════════════════
  // SMARTPHONES  (80)
  // ════════════════════════════════════════════════════════════════════════════

  // Apple iPhone (20)
  ...s("Apple", "brand_apple", "cat_phone", "smartphones", "Smartphones", 799, 1599, IMG.phones, ["flagship", "5g", "ios"],
    "The latest iPhone combines the A18 Pro chip with advanced camera features, titanium design and all-day battery life.", [
      "iPhone 16 Pro Max 256GB Natural Titanium",
      "iPhone 16 Pro Max 512GB Black Titanium",
      "iPhone 16 Pro Max 1TB Desert Titanium",
      "iPhone 16 Pro Max 512GB White Titanium",
      "iPhone 16 Pro 256GB Natural Titanium",
      "iPhone 16 Pro 512GB Black Titanium",
      "iPhone 16 Pro 1TB Desert Titanium",
      "iPhone 16 Pro 256GB White Titanium",
      "iPhone 16 Plus 256GB Ultramarine",
      "iPhone 16 Plus 512GB Black",
      "iPhone 16 128GB Teal",
      "iPhone 16 256GB Pink",
      "iPhone 15 Pro Max 256GB Natural Titanium",
      "iPhone 15 Pro 512GB Black Titanium",
      "iPhone 15 256GB Black",
      "iPhone 15 128GB Pink",
      "iPhone 14 128GB Midnight",
      "iPhone 14 Plus 256GB Blue",
      "iPhone SE 3rd Gen 64GB Midnight",
      "iPhone SE 3rd Gen 128GB Starlight",
    ]),

  // Samsung Galaxy (20)
  ...s("Samsung", "brand_samsung", "cat_phone", "smartphones", "Smartphones", 349, 1299, IMG.phones, ["android", "5g", "samsung"],
    "Galaxy smartphones feature cutting-edge displays, powerful cameras and AI features powered by Snapdragon or Exynos.", [
      "Galaxy S25 Ultra 256GB Titanium Black",
      "Galaxy S25 Ultra 512GB Titanium Silver",
      "Galaxy S25 Ultra 1TB Titanium Blue",
      "Galaxy S25+ 256GB Phantom Black",
      "Galaxy S25+ 512GB Ice Blue",
      "Galaxy S25 256GB Navy",
      "Galaxy S25 512GB Sky Blue",
      "Galaxy S24 FE 128GB Graphite",
      "Galaxy S24 FE 256GB Blue",
      "Galaxy A56 5G 128GB Awesome Violet",
      "Galaxy A56 5G 256GB Awesome Navy",
      "Galaxy A36 5G 128GB Black",
      "Galaxy A36 5G 256GB Silver",
      "Galaxy Z Fold 6 256GB Navy",
      "Galaxy Z Fold 6 512GB Silver",
      "Galaxy Z Flip 6 256GB Yellow",
      "Galaxy Z Flip 6 512GB Crafted Black",
      "Galaxy A16 128GB Light Green",
      "Galaxy A16 256GB Teal Blue",
      "Galaxy M35 5G 128GB Thunder Gray",
    ]),

  // Google Pixel (15)
  ...s("Google", "brand_google", "cat_phone", "smartphones", "Smartphones", 449, 1099, IMG.phones, ["android", "5g", "google", "ai"],
    "Pixel phones run pure Android with exclusive AI features, the best computational photography and guaranteed OS updates.", [
      "Pixel 9 Pro XL 256GB Obsidian",
      "Pixel 9 Pro XL 512GB Porcelain",
      "Pixel 9 Pro 128GB Obsidian",
      "Pixel 9 Pro 256GB Porcelain",
      "Pixel 9 128GB Obsidian",
      "Pixel 9 256GB Rose Quartz",
      "Pixel 8a 128GB Obsidian",
      "Pixel 8a 256GB Bay",
      "Pixel 8 Pro 128GB Obsidian",
      "Pixel 8 Pro 256GB Bay",
      "Pixel 8 128GB Obsidian",
      "Pixel 8 256GB Hazel",
      "Pixel 7a 128GB Charcoal",
      "Pixel 7 128GB Snow",
      "Pixel 7 256GB Lemongrass",
    ]),

  // Xiaomi / OnePlus / OPPO / Others (25)
  ...s("Xiaomi", "brand_xiaomi", "cat_phone", "smartphones", "Smartphones", 299, 1399, IMG.phones, ["android", "5g", "xiaomi"],
    "Xiaomi delivers flagship performance with innovative camera systems and fast charging at competitive price points.", [
      "Xiaomi 14 Ultra 512GB Black",
      "Xiaomi 14 Ultra 1TB Titanium",
      "Xiaomi 14 256GB Black",
      "Xiaomi 14 512GB White",
      "Xiaomi 13T Pro 256GB Black",
    ]),
  ...s("OnePlus", "brand_oneplus", "cat_phone", "smartphones", "Smartphones", 299, 999, IMG.phones, ["android", "5g", "oneplus"],
    "OnePlus offers fast and smooth Android experience with Hasselblad cameras and flagship Snapdragon processors.", [
      "OnePlus 13 256GB Midnight Ocean",
      "OnePlus 13 512GB Silky Black",
      "OnePlus 12 256GB Flowy Emerald",
      "OnePlus 12 512GB Silky Black",
      "OnePlus Nord 4 256GB Mercurial Silver",
    ]),
  ...s("OPPO", "brand_oppo", "cat_phone", "smartphones", "Smartphones", 249, 1199, IMG.phones, ["android", "5g", "oppo"],
    "OPPO excels in ultra-fast charging and AI-powered camera technology with elegant design language.", [
      "OPPO Find X8 Pro 512GB Space Black",
      "OPPO Find X8 256GB Space Black",
      "OPPO Reno 12 Pro 512GB Space Brown",
      "OPPO A79 5G 256GB Mystery Black",
      "OPPO Reno 11 256GB Gray",
      "Sony Xperia 1 VI 256GB Black",
      "Sony Xperia 5 VI 128GB Black",
      "Motorola Edge 50 Ultra 512GB Peach Fuzz",
      "ASUS ROG Phone 8 Pro 512GB Rebel Grey",
      "Nothing Phone 2a Plus 256GB Black",
      "Nokia XR21 128GB Black",
      "Realme GT 6T 256GB Fluid Silver",
      "Vivo X100 Pro 512GB Asteroid Black",
      "Motorola Razr 50 Ultra 512GB Scarlet Wave",
      "ASUS Zenfone 11 Ultra 256GB Eternal Black",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // LAPTOPS  (80)
  // ════════════════════════════════════════════════════════════════════════════

  // Apple MacBook (20)
  ...s("Apple", "brand_apple", "cat_laptop", "laptops-computers", "Laptops & Computers", 999, 3999, IMG.laptops, ["apple", "macos", "ultrabook"],
    "MacBook combines the power of Apple Silicon M-series chips with an incredibly thin design and all-day battery life.", [
      "MacBook Pro 16-inch M4 Max 1TB Space Black",
      "MacBook Pro 16-inch M4 Max 2TB Silver",
      "MacBook Pro 16-inch M4 Pro 512GB Space Black",
      "MacBook Pro 16-inch M4 Pro 1TB Space Black",
      "MacBook Pro 14-inch M4 Max 1TB Space Black",
      "MacBook Pro 14-inch M4 Pro 512GB Silver",
      "MacBook Pro 14-inch M4 Pro 1TB Space Black",
      "MacBook Pro 14-inch M4 256GB Silver",
      "MacBook Air 15-inch M3 256GB Midnight",
      "MacBook Air 15-inch M3 512GB Starlight",
      "MacBook Air 15-inch M3 16GB 512GB Space Gray",
      "MacBook Air 15-inch M2 256GB Midnight",
      "MacBook Air 13-inch M3 256GB Midnight",
      "MacBook Air 13-inch M3 512GB Starlight",
      "MacBook Air 13-inch M3 16GB 256GB Space Gray",
      "MacBook Air 13-inch M2 256GB Midnight",
      "MacBook Air 13-inch M2 512GB Silver",
      "MacBook Air 13-inch M2 8GB 512GB Starlight",
      "Mac mini M4 256GB Silver",
      "Mac mini M4 Pro 512GB Silver",
    ]),

  // Dell (20)
  ...s("Dell", "brand_dell", "cat_laptop", "laptops-computers", "Laptops & Computers", 699, 3499, IMG.laptops, ["windows", "dell", "laptop"],
    "Dell laptops range from ultra-thin XPS ultrabooks to powerful Alienware gaming rigs for every need.", [
      "Dell XPS 15 9530 RTX 4060 1TB Platinum Silver",
      "Dell XPS 15 9530 RTX 4070 2TB Platinum Silver",
      "Dell XPS 13 9340 512GB Platinum Silver",
      "Dell XPS 13 9340 1TB Graphite",
      "Dell XPS 14 9440 RTX 4050 1TB Ice",
      "Dell XPS 16 9640 RTX 4070 32GB 1TB Silver",
      "Dell Inspiron 16 i7 16GB 512GB Silver",
      "Dell Inspiron 15 i5 16GB 512GB Platinum",
      "Dell Inspiron 15 i7 16GB 1TB Black",
      "Dell Latitude 14 i7 16GB 512GB Titan Gray",
      "Dell Latitude 15 i7 32GB 1TB Black",
      "Dell G15 RTX 4060 16GB 512GB Specter Green",
      "Dell G16 RTX 4070 32GB 1TB Shadow Gray",
      "Dell Alienware m16 R2 RTX 4080 32GB Dark",
      "Dell Alienware m18 R2 RTX 4090 64GB Dark",
      "Dell Vostro 15 i5 16GB 512GB Black",
      "Dell Precision 3581 i9 32GB 1TB Black",
      "Dell Inspiron 14 i5 16GB 512GB Silver",
      "Dell Latitude 7450 i7 16GB 512GB Silver",
      "Dell XPS Desktop 8960 RTX 4070 1TB Black",
    ]),

  // HP (20)
  ...s("HP", "brand_hp", "cat_laptop", "laptops-computers", "Laptops & Computers", 499, 2999, IMG.laptops, ["windows", "hp", "laptop"],
    "HP offers premium Spectre ultrabooks, versatile Envy convertibles, and powerful OMEN gaming laptops.", [
      "HP Spectre x360 14 OLED i7 32GB 1TB Night Fall",
      "HP Spectre x360 14 OLED i5 16GB 512GB Silver",
      "HP Spectre x360 16 OLED i7 32GB 1TB Nocturne",
      "HP Envy 17 i7 32GB 1TB Silver",
      "HP Envy 15 i7 16GB 1TB Silver",
      "HP Envy x360 15 Ryzen 7 16GB 512GB Silver",
      "HP Envy x360 13 Ryzen 5 16GB 512GB Teal",
      "HP Pavilion 15 i5 16GB 512GB Warm Gold",
      "HP Pavilion 16 i7 RTX 3050 16GB 1TB Silver",
      "HP OMEN 16 RTX 4070 16GB 1TB Shadow Black",
      "HP OMEN 17 RTX 4080 32GB 1TB Shadow Black",
      "HP OMEN Transcend 14 RTX 4070 32GB 2TB White",
      "HP EliteBook 840 G11 i7 16GB 512GB Silver",
      "HP EliteBook 860 G11 i7 32GB 1TB Gray",
      "HP ProBook 450 G10 i5 16GB 512GB Silver",
      "HP Victus 15 RTX 3050 16GB 512GB Mica Silver",
      "HP Victus 16 RTX 4060 16GB 1TB Performance Blue",
      "HP ZBook Studio G10 i9 64GB 2TB Turbo Silver",
      "HP Dragonfly Pro i7 32GB 1TB Cosmic Blue",
      "HP Laptop 15 i3 8GB 256GB Natural Silver",
    ]),

  // Lenovo / ASUS / Others (20)
  ...s("Lenovo", "brand_lenovo", "cat_laptop", "laptops-computers", "Laptops & Computers", 599, 2799, IMG.laptops, ["windows", "lenovo", "laptop"],
    "Lenovo ThinkPad, IdeaPad, Yoga and Legion cover business, everyday and gaming needs with reliability.", [
      "Lenovo ThinkPad X1 Carbon Gen 12 i7 32GB 1TB",
      "Lenovo ThinkPad X1 Yoga Gen 9 i7 32GB 1TB",
      "Lenovo IdeaPad Pro 5 i7 RTX 4060 16GB 1TB",
      "Lenovo IdeaPad Slim 5 i5 16GB 512GB Cloud Grey",
      "Lenovo Yoga 9 2-in-1 OLED i7 32GB 1TB Oatmeal",
      "Lenovo Legion 7i Gen 9 RTX 4080 32GB 2TB Black",
      "Lenovo Legion 5i Gen 9 RTX 4060 32GB 1TB Grey",
      "Lenovo LOQ 15 RTX 4050 16GB 512GB Luna Grey",
      "ASUS ROG Zephyrus G16 RTX 4090 32GB 2TB Grey",
      "ASUS ROG Strix SCAR 18 RTX 4090 64GB 4TB Black",
      "ASUS Vivobook Pro 15 OLED RTX 4060 16GB 512GB",
      "ASUS ZenBook 14 OLED i7 16GB 1TB Jasper Green",
      "ASUS TUF Gaming F15 RTX 4060 16GB 512GB Gray",
      "MSI Raider GE78 HX RTX 4090 32GB 2TB Black",
      "MSI Stealth 16 RTX 4090 32GB 2TB Lunar Gray",
      "Acer Swift Go 14 OLED i7 16GB 1TB Pure Silver",
      "Acer Predator Helios 18 RTX 4090 32GB 2TB Black",
      "Acer Nitro 5 RTX 4060 16GB 512GB Black",
      "Samsung Galaxy Book4 Pro 360 i7 16GB 1TB Navy",
      "Microsoft Surface Laptop 6 i7 32GB 1TB Platinum",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // TABLETS  (40)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Apple", "brand_apple", "cat_tablet", "tablets", "Tablets", 329, 1799, IMG.tablets, ["ipad", "apple", "ios"],
    "iPad combines the performance of an M-series chip with the versatility of Apple Pencil and keyboard accessories.", [
      "iPad Pro 13-inch M4 256GB Wi-Fi Space Black",
      "iPad Pro 13-inch M4 512GB Wi-Fi Silver",
      "iPad Pro 13-inch M4 256GB Wi-Fi Cellular Space Black",
      "iPad Pro 11-inch M4 256GB Wi-Fi Space Black",
      "iPad Pro 11-inch M4 512GB Wi-Fi Silver",
      "iPad Pro 11-inch M4 128GB Wi-Fi Cellular Space Black",
      "iPad Air 13-inch M2 256GB Wi-Fi Blue",
      "iPad Air 13-inch M2 128GB Wi-Fi Starlight",
      "iPad Air 11-inch M2 256GB Wi-Fi Purple",
      "iPad Air 11-inch M2 128GB Wi-Fi Blue",
      "iPad mini 7 256GB Wi-Fi Starlight",
      "iPad mini 7 128GB Wi-Fi Space Gray",
      "iPad 10th Gen 256GB Wi-Fi Silver",
      "iPad 10th Gen 64GB Wi-Fi Blue",
      "iPad 9th Gen 64GB Wi-Fi Silver",
    ]),

  ...s("Samsung", "brand_samsung", "cat_tablet", "tablets", "Tablets", 199, 1199, IMG.tablets, ["android", "samsung", "tablet"],
    "Galaxy Tab S series offers premium AMOLED displays, powerful processors and seamless integration with Samsung DeX.", [
      "Galaxy Tab S10 Ultra 512GB Wi-Fi Titanium Gray",
      "Galaxy Tab S10 Ultra 256GB Wi-Fi Titanium Silver",
      "Galaxy Tab S10 FE 256GB Wi-Fi Pink Gold",
      "Galaxy Tab S10 FE 128GB Wi-Fi Silver",
      "Galaxy Tab S10 Plus 512GB Wi-Fi Titanium Gray",
      "Galaxy Tab S10 256GB Wi-Fi Silver",
      "Galaxy Tab S9 Ultra 512GB Wi-Fi Graphite",
      "Galaxy Tab S9 FE 256GB Wi-Fi Mint",
      "Galaxy Tab S9 FE 128GB Wi-Fi Gray",
      "Galaxy Tab A9 Plus 256GB Wi-Fi Navy",
      "Galaxy Tab A9 Plus 128GB Wi-Fi Gray",
      "Galaxy Tab A8 128GB Wi-Fi Gray",
      "Galaxy Tab A8 64GB Wi-Fi Silver",
      "Galaxy Tab Active5 128GB Wi-Fi Black",
      "Galaxy Tab S6 Lite 128GB Wi-Fi Oxford Gray",
    ]),

  ...s("Lenovo", "brand_lenovo", "cat_tablet", "tablets", "Tablets", 149, 599, IMG.tablets, ["android", "tablet", "lenovo"],
    "Lenovo tablets offer versatile productivity options with optional keyboard folio covers for students and professionals.", [
      "Lenovo Tab P12 Pro 256GB Storm Gray",
      "Lenovo Tab P11 Pro Gen 2 256GB Storm Gray",
      "Amazon Fire HD 10 Plus 32GB Slate",
      "Amazon Fire HD 10 64GB Olive",
      "Amazon Fire Max 11 64GB Gray",
      "Amazon Fire HD 8 Plus 32GB Black",
      "Microsoft Surface Pro 11 512GB Platinum",
      "Microsoft Surface Pro 11 1TB Graphite",
      "Xiaomi Pad 7 Pro 512GB Gray",
      "Xiaomi Pad 7 256GB Black",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // AUDIO  (60)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Sony", "brand_sony", "cat_audio", "audio-headphones", "Audio & Headphones", 49, 399, IMG.audio, ["headphones", "wireless", "noise-cancelling"],
    "Sony's market-leading noise cancellation and spatial sound technology deliver immersive audio for music and travel.", [
      "Sony WH-1000XM5 Wireless Headphones Black",
      "Sony WH-1000XM5 Wireless Headphones Silver",
      "Sony WH-1000XM5 Wireless Headphones Midnight Blue",
      "Sony WF-1000XM5 Wireless Earbuds Black",
      "Sony WF-1000XM5 Wireless Earbuds Silver",
      "Sony WF-C700N Wireless Earbuds Black",
      "Sony WF-C700N Wireless Earbuds Sage",
      "Sony SRS-XB100 Portable Bluetooth Speaker Black",
      "Sony SRS-XG300 Portable Bluetooth Speaker Black",
      "Sony SRS-XP500 Portable Party Speaker Black",
      "Sony MDR-7506 Professional Studio Headphones",
      "Sony WH-CH720N Wireless Headphones Black",
      "Sony WH-CH720N Wireless Headphones Blue",
      "Sony WI-C100 Wireless In-Ear Headphones Black",
      "Sony Inzone H9 Wireless Gaming Headset White",
    ]),

  ...s("Bose", "brand_bose", "cat_audio", "audio-headphones", "Audio & Headphones", 99, 449, IMG.audio, ["headphones", "wireless", "premium", "noise-cancelling"],
    "Bose combines world-class acoustic engineering with luxurious comfort for the ultimate listening experience.", [
      "Bose QuietComfort Ultra Headphones Black",
      "Bose QuietComfort Ultra Headphones White Smoke",
      "Bose QuietComfort 45 Headphones Black",
      "Bose QuietComfort 45 Headphones White Smoke",
      "Bose QuietComfort Ultra Earbuds Black",
      "Bose QuietComfort Ultra Earbuds White Smoke",
      "Bose QuietComfort Earbuds II Black",
      "Bose QuietComfort Earbuds II Soapstone",
      "Bose SoundLink Flex Portable Speaker Black",
      "Bose SoundLink Flex Portable Speaker Blue Dusk",
      "Bose SoundLink Max Portable Speaker Black",
      "Bose Smart Soundbar 900 Black",
      "Bose Smart Soundbar 600 Black",
      "Bose Smart Speaker 500 Black",
      "Bose TV Speaker Black",
    ]),

  ...s("JBL", "brand_jbl", "cat_audio", "audio-headphones", "Audio & Headphones", 49, 299, IMG.audio, ["speaker", "portable", "waterproof"],
    "JBL delivers bold sound in rugged, waterproof designs built for parties, outdoors and everyday adventures.", [
      "JBL Charge 5 Portable Bluetooth Speaker Black",
      "JBL Charge 5 Portable Bluetooth Speaker Blue",
      "JBL Charge 5 Portable Bluetooth Speaker Red",
      "JBL Flip 7 Portable Speaker Black",
      "JBL Flip 7 Portable Speaker Blue",
      "JBL Xtreme 4 Portable Bluetooth Speaker Black",
      "JBL Tune Buds True Wireless Earbuds Black",
      "JBL Tune Buds True Wireless Earbuds White",
      "JBL Live Pro 2 TWS Earbuds Black",
      "JBL Live 770NC Wireless Headphones Black",
      "JBL Live 660NC Wireless Headphones Black",
      "JBL Quantum 910 Wireless Gaming Headset",
      "JBL Quantum 350 Wireless Gaming Headset",
      "JBL Boombox 3 Portable Speaker Black",
      "JBL PartyBox 110 Portable Party Speaker Black",
    ]),

  ...s("Apple", "brand_apple", "cat_audio", "audio-headphones", "Audio & Headphones", 129, 549, IMG.audio, ["apple", "wireless", "airpods"],
    "AirPods deliver a magical wireless audio experience with seamless Apple ecosystem integration and spatial audio.", [
      "Apple AirPods Pro 2nd Gen USB-C White",
      "Apple AirPods 3rd Gen Lightning White",
      "Apple AirPods Max Silver",
      "Apple AirPods Max Midnight",
      "Sennheiser HD 660S2 Over-Ear Headphones Black",
      "Sennheiser Momentum 4 Wireless Black",
      "Marshall Emberton II Portable Speaker Black",
      "Marshall Stanmore III Home Speaker Black",
      "Anker Soundcore Space One Wireless Headphones Black",
      "Jabra Evolve2 75 Wireless Headset Black",
      "Jabra Elite 10 True Wireless Earbuds Black",
      "Beats Studio Pro Wireless Headphones Black",
      "Beats Fit Pro True Wireless Earbuds Black",
      "Bang & Olufsen Beoplay H95 Wireless Headphones Navy",
      "Shure AONIC 50 Gen 2 Wireless Headphones Black",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // CAMERAS  (40)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Canon", "brand_canon", "cat_camera", "cameras-photography", "Cameras & Photography", 199, 3999, IMG.cameras, ["canon", "mirrorless", "dslr"],
    "Canon EOS R mirrorless cameras deliver professional image quality with fast autofocus and rich lens ecosystem.", [
      "Canon EOS R5 Mark II Body",
      "Canon EOS R5 Mark II with RF 24-105mm F4L Lens",
      "Canon EOS R6 Mark II Body",
      "Canon EOS R6 Mark II with RF 24-105mm Lens",
      "Canon EOS R50 Body Black",
      "Canon EOS R50 Body White",
      "Canon EOS R100 Body Black",
      "Canon EOS R100 with RF-S 18-45mm Lens",
      "Canon EOS R10 Body Black",
      "Canon EOS R10 with RF-S 18-45mm Lens",
      "Canon EOS R8 Body",
      "Canon PowerShot V10 Compact Camera Black",
      "Canon RF 50mm f/1.8 STM Lens",
      "Canon EOS R7 Body Black",
      "Canon RF 85mm f/2 Macro IS STM Lens",
    ]),

  ...s("Sony", "brand_sony", "cat_camera", "cameras-photography", "Cameras & Photography", 499, 4999, IMG.cameras, ["sony", "mirrorless", "fullframe"],
    "Sony Alpha mirrorless cameras set the benchmark for autofocus speed, video capability and low-light performance.", [
      "Sony Alpha 7 IV Full-Frame Mirrorless Camera Body",
      "Sony Alpha 7 IV with FE 28-70mm Lens",
      "Sony Alpha 7C II Body Silver",
      "Sony Alpha 7C II Body Black",
      "Sony Alpha 6700 APS-C Camera Body",
      "Sony Alpha 6700 with 18-135mm Lens",
      "Sony Alpha ZV-E10 II Camera Body Black",
      "Sony ZV-1 II Compact Camera Black",
      "Sony FX30 Cinema Line Camera",
      "Sony Alpha 9 III Body Black",
      "Sony RX100 VII Compact Camera",
      "Sony RX10 IV Bridge Camera",
      "Sony FE 85mm f/1.8 Lens",
      "Sony FE 24-70mm f/2.8 GM II Lens",
      "Sony Vlogging Kit ZV-E10 II Bundle",
    ]),

  ...s("Canon", "brand_canon", "cat_camera", "cameras-photography", "Cameras & Photography", 99, 999, IMG.cameras, ["camera", "photography", "lens"],
    "Leading imaging technology delivering stunning photos and videos for beginners and enthusiast photographers.", [
      "Nikon Z6 III Body Black",
      "Nikon Z50 II Body Black",
      "Nikon Z30 with 16-50mm Lens Kit",
      "Fujifilm X-T5 Body Black",
      "Fujifilm X-S20 Body Black",
      "Fujifilm Instax Mini 12 Camera Mint Green",
      "DJI Osmo Pocket 3 Creator Combo",
      "GoPro HERO13 Black",
      "GoPro HERO13 Black Creator Edition",
      "Insta360 X4 360-Degree Camera",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // SMART HOME  (40)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Amazon", "brand_amazon", "cat_smarthome", "smart-home", "Smart Home", 19, 299, IMG.smarthome, ["smart-home", "alexa", "amazon"],
    "Amazon Echo and Ring devices use Alexa to make your home smarter, safer and more convenient.", [
      "Amazon Echo Dot 5th Gen Charcoal",
      "Amazon Echo Dot 5th Gen Glacier White",
      "Amazon Echo 4th Gen Charcoal",
      "Amazon Echo Show 8 Charcoal",
      "Amazon Echo Show 10 Charcoal",
      "Amazon Echo Show 15 Charcoal",
      "Amazon Smart Plug Mini 15A",
      "Amazon Echo Buds 2nd Gen Black",
      "Fire TV Stick 4K Max 3rd Gen",
      "Amazon Astro Household Robot",
    ]),

  ...s("Google", "brand_google", "cat_smarthome", "smart-home", "Smart Home", 29, 349, IMG.smarthome, ["smart-home", "google", "nest"],
    "Google Nest smart speakers, displays, cameras and thermostats create a seamless connected home experience.", [
      "Google Nest Hub Max Charcoal",
      "Google Nest Hub 2nd Gen Charcoal",
      "Google Nest Hub 2nd Gen Chalk",
      "Google Nest Mini 2nd Gen Charcoal",
      "Google Nest Audio Charcoal",
      "Google Nest WiFi Pro 6E 3-Pack",
      "Google Nest Cam Indoor Wired Snow",
      "Google Nest Cam Outdoor Battery",
      "Google Nest Doorbell Battery",
      "Google Nest Thermostat Snow",
    ]),

  ...s("Philips", "brand_philips", "cat_smarthome", "smart-home", "Smart Home", 14, 649, IMG.smarthome, ["smart-home", "philips", "hue", "lighting"],
    "Philips Hue smart lighting transforms your home with millions of colors, scenes and voice-controlled ambiance.", [
      "Philips Hue White and Color Ambiance Starter Kit",
      "Philips Hue Bridge 2.0",
      "Philips Hue Play HDMI Sync Box",
      "Philips Hue White and Color Ambiance Bulb E26",
      "Philips Hue Bloom Table Light White",
      "Philips Hue Lightstrip Plus 2m Extension",
      "Philips Hue Signe Floor Lamp Black",
      "Philips Smart Air Purifier 2000i",
      "Philips Hue Tap Dial Switch",
      "Philips 55-inch OLED908 4K UHD Android TV",
    ]),

  ...s("Philips", "brand_philips", "cat_smarthome", "smart-home", "Smart Home", 29, 799, IMG.smarthome, ["smart-home", "security", "automation"],
    "Smart home security and automation products to protect and streamline your connected home ecosystem.", [
      "Ring Video Doorbell Pro 2",
      "Ring Alarm Pro 8-Piece Kit",
      "Nest Protect Smoke and CO Alarm",
      "Ecobee SmartThermostat Premium",
      "August WiFi Smart Lock Black",
      "Arlo Pro 5S 2K Wireless Camera White",
      "TP-Link Kasa Smart Plug 2-Pack",
      "Govee LED Strip Lights 65ft RGBIC",
      "iRobot Roomba j9+ Self-Emptying Robot Vacuum",
      "Roborock S8 Pro Ultra Robot Vacuum and Mop",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // MEN'S CLOTHING  (80)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Nike", "brand_nike", "cat_mens", "mens-clothing", "Men's Clothing", 29, 249, IMG.mens, ["nike", "sportswear", "mens"],
    "Nike men's apparel combines performance Dri-FIT technology with classic Sportswear silhouettes for every occasion.", [
      "Nike Therma-FIT Repel Men's Running Jacket Black",
      "Nike Sportswear Tech Fleece Full-Zip Hoodie Black",
      "Nike Sportswear Club Fleece Crew-Neck Sweatshirt Navy",
      "Nike Dri-FIT Academy Men's Football Shorts Navy",
      "Nike Sportswear Tech Fleece Men's Joggers Black",
      "Nike Dri-FIT Rise 365 Men's Running T-Shirt Gray",
      "Nike Sportswear Premium Essentials T-Shirt White",
      "Nike Windrunner Men's Running Jacket Blue",
      "Nike Dri-FIT Challenger Men's Running Shorts",
      "Nike Therma Men's Training Hoodie Carbon",
      "Nike Pro Men's Tight Compression Base Layer Black",
      "Nike Yoga Dri-FIT Men's Long-Sleeve Top",
      "Nike Air Men's Long-Sleeve Fitness Top",
      "Nike Sportswear Woven Unlined Wind Jacket",
      "Nike Dri-FIT Legend Men's Training Pants Gray",
      "Nike Storm-FIT ADV Men's Golf Jacket Black",
      "Nike Dri-FIT Men's Basketball T-Shirt White",
      "Nike Dri-FIT Men's Fitness T-Shirt",
      "Nike Yoga Infinalon 7-Inch Unlined Short",
      "Nike Dri-FIT ADV Men's Short-Sleeve Top",
    ]),

  ...s("Adidas", "brand_adidas", "cat_mens", "mens-clothing", "Men's Clothing", 24, 219, IMG.mens, ["adidas", "sportswear", "mens"],
    "Adidas men's clothing blends iconic three-stripe style with performance AEROREADY and Primegreen technology.", [
      "Adidas Tiro 23 Competition Training Jacket Black",
      "Adidas Essentials 3-Stripes Joggers Black",
      "Adidas Adizero Lightweight Running T-Shirt White",
      "Adidas AEROREADY Designed for Training Hoodie",
      "Adidas Tiro 23 League Training Pants Black",
      "Adidas Studio Lounge Graphic T-Shirt White",
      "Adidas Essentials Fleece Training Pants Navy",
      "Adidas Future Icons Woven Track Jacket Black",
      "Adidas Run Icons Running T-Shirt Green",
      "Adidas Designed 4 Training Shorts Black",
      "Adidas Terrex Skychaser 2.0 GORE-TEX Jacket",
      "Adidas Performance Primegreen Polo Shirt",
      "Adidas Sportswear Colorblock Fleece Hoodie",
      "Adidas Yoga Studio Joggers Gray",
      "Adidas Tiro League Quarter-Zip Top",
      "Adidas Techfit 3-Bar Training Long Tights",
      "Adidas Lounge Fleece Crew Sweatshirt Navy",
      "Adidas Z.N.E. Winterized Tracksuit Jacket",
      "Adidas Ultimate365 Printed Golf Polo",
      "Adidas Entrada 22 Training Jersey White",
    ]),

  ...s("H&M", "brand_hm", "cat_mens", "mens-clothing", "Men's Clothing", 9, 89, IMG.mens, ["hm", "casual", "mens"],
    "H&M offers trend-forward men's essentials from Oxford shirts to relaxed linen trousers at everyday prices.", [
      "H&M Slim Fit Oxford Shirt Blue",
      "H&M Regular Fit Cotton T-Shirt White",
      "H&M Relaxed Fit Linen Blend Trousers Beige",
      "H&M Regular Fit Sweatshirt Dark Gray",
      "H&M Slim Fit Suit Jacket Black",
      "H&M Regular Fit Linen Shirt Light Blue",
      "H&M Slim Fit Chinos Beige",
      "H&M Regular Fit Hoodie Navy",
      "H&M Regular Fit Cotton Shorts Gray",
      "H&M Slim Fit Turtleneck Sweater Black",
    ]),
  ...s("Uniqlo", "brand_uniqlo", "cat_mens", "mens-clothing", "Men's Clothing", 14, 119, IMG.mens, ["uniqlo", "essential", "mens"],
    "Uniqlo LifeWear essentials combine Japanese quality craftsmanship with AIRism, HEATTECH and Ultra Light Down technology.", [
      "Uniqlo AIRism Cotton Blend V-Neck T-Shirt White",
      "Uniqlo HEATTECH Extra Warm Crew Neck T-Shirt Black",
      "Uniqlo Ultra Stretch Slim-Fit Jeans Blue",
      "Uniqlo Merino Blend V-Neck Sweater Navy",
      "Uniqlo Cotton Linen Blend Short-Sleeve Shirt",
      "Uniqlo Relaxed Ankle Pants Gray",
      "Uniqlo Supima Cotton Crew Neck T-Shirt White",
      "Uniqlo AIRism Mesh Full-Zip Hoodie Black",
      "Uniqlo HEATTECH Ultra Warm Turtleneck Black",
      "Uniqlo Blocktech Hooded Parka Black",
    ]),
  ...s("Levi's", "brand_levis", "cat_mens", "mens-clothing", "Men's Clothing", 39, 149, IMG.mens, ["levis", "denim", "mens"],
    "Levi's iconic denim jeans, trucker jackets and casual shirts deliver authentic American style since 1873.", [
      "Levi's 511 Slim Fit Jeans Blue",
      "Levi's 501 Original Fit Jeans Dark Stonewash",
      "Levi's Sherpa Trucker Jacket Navy",
      "Levi's Classic Straight Fit Jeans Black",
      "Levi's Relaxed Taper Jeans Light Indigo",
      "Calvin Klein Men's Slim Fit Dress Shirt White",
      "Calvin Klein Modern Essential Crewneck T-Shirt",
      "Tommy Hilfiger Classic Polo Shirt Navy",
      "Ralph Lauren Polo Classic Fit T-Shirt Gray",
      "Zara Slim Fit Check Blazer Blue Check",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // WOMEN'S CLOTHING  (80)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Zara", "brand_zara", "cat_womens", "womens-clothing", "Women's Clothing", 19, 199, IMG.womens, ["zara", "fashion", "womens"],
    "Zara women's collection blends current runway trends with versatile everyday essentials at accessible prices.", [
      "Zara Linen Blend Blazer Ecru",
      "Zara Flowing Wrap Dress Black",
      "Zara Printed Slip Dress Floral",
      "Zara High-Waist Straight Jeans Blue",
      "Zara Linen Blend Wide-Leg Pants Ecru",
      "Zara Cropped V-Neck T-Shirt White",
      "Zara Satin Effect Midi Skirt Ecru",
      "Zara Oversized Trench Coat Camel",
      "Zara Knitwear Zip-Up Cardigan Beige",
      "Zara Ruffled Mini Skirt Pink",
      "Zara Tailored Wool Blend Coat Gray",
      "Zara Pleated Midi Dress Sage Green",
      "Zara Leather-Effect Trousers Black",
      "Zara Embroidered Maxi Dress White",
      "Zara Ribbed Fitted Mini Dress Black",
      "Zara Sequined Long Dress Black",
      "Zara Flowing Printed Shorts Floral",
      "Zara Washed Effect Straight Jeans Light Blue",
      "Zara Velvet Blazer Burgundy",
      "Zara Textured Short Sleeve Bodysuit Cream",
    ]),

  ...s("H&M", "brand_hm", "cat_womens", "womens-clothing", "Women's Clothing", 9, 99, IMG.womens, ["hm", "casual", "womens"],
    "H&M women's range covers everyday basics to occasion wear with sustainable conscious collection pieces.", [
      "H&M Ribbed Jersey Dress Black",
      "H&M Linen Blend Shirt Dress White",
      "H&M Relaxed Fit Cotton T-Shirt Gray",
      "H&M Regular Fit Linen Trousers Beige",
      "H&M Wide-Leg High Jeans Blue",
      "H&M Loose-Fit Hoodie Light Gray",
      "H&M Slim Fit Turtleneck Sweater Gray",
      "H&M Patterned A-Line Skirt Floral",
      "H&M Regular Fit Cotton Shorts White",
      "H&M Oversized Padded Jacket Beige",
      "H&M Fitted Jersey Bodysuit Black",
      "H&M Regular Fit Linen Top White",
      "H&M Wrapover Midi Dress Sage Green",
      "H&M Balloon-Sleeve Blouse White",
      "H&M Straight Regular Ankle Jeans Blue",
      "H&M Pleated Jersey Skirt Olive Green",
      "H&M Long-Sleeved Crop Top Black",
      "H&M Regular Fit Cotton Dress Pink",
      "H&M Smocked Maxi Dress Blue",
      "H&M Modal-Blend Leggings Black",
    ]),

  ...s("Nike", "brand_nike", "cat_womens", "womens-clothing", "Women's Clothing", 24, 219, IMG.womens, ["nike", "sportswear", "womens"],
    "Nike women's activewear delivers Dri-FIT performance alongside Phoenix Fleece comfort for sport and street.", [
      "Nike Dri-FIT One Slim Fit Women's Tank",
      "Nike Yoga Luxe Women's Short-Sleeve Top",
      "Nike Therma-FIT Women's Training Hoodie",
      "Nike Sportswear Phoenix Fleece Women's Hoodie",
      "Nike Sportswear Women's Mid-Rise Leggings Black",
      "Nike Dri-FIT High-Waist 3in Women's Running Shorts",
      "Nike One Dri-FIT Women's Tight Training Pants",
      "Nike Air Women's Mid-Rise Jogger Pants",
      "Nike Pro Women's 5in Compression Shorts",
      "Nike Dri-FIT Victory Women's Golf Polo",
      "Nike Yoga Dri-FIT Women's Long-Sleeve Crop Top",
      "Nike Sportswear Club Fleece Women's Wide-Leg Pants",
      "Nike Essential Women's 3in Swim Shorts",
      "Nike Dri-FIT Get Fit Women's Training Pants",
      "Nike Tempo Luxe Women's Running Shorts",
      "Nike Yoga Layered Women's Sports Bra",
      "Nike One Women's Standard Full-Coverage Sports Bra",
      "Nike Sportswear Essential Women's Woven Jacket",
      "Nike Trail Dri-FIT Downpour Women's Running Jacket",
      "Nike Swoosh Women's 1-Piece Swimsuit Black",
    ]),

  ...s("Levi's", "brand_levis", "cat_womens", "womens-clothing", "Women's Clothing", 29, 159, IMG.womens, ["denim", "casual", "womens"],
    "Timeless women's denim and casual wear combining iconic Levi's fits with contemporary style updates.", [
      "Levi's Women's 711 Skinny Jeans Blue",
      "Levi's Women's Mile High Super Skinny Jeans Black",
      "Calvin Klein Women's Twist Back Tank White",
      "Calvin Klein Women's Slim-Fit Ponte Pant Black",
      "Tommy Hilfiger Women's Logo Crew-Neck Sweatshirt",
      "Tommy Hilfiger Women's Colorblock Polo Dress White",
      "Banana Republic Sloan Slim Straight-Fit Pant Navy",
      "Gap Women's Denim Jacket Light Indigo",
      "Gap Women's Relaxed Fit Wide-Leg Chinos Beige",
      "Free People Women's Always The One Slip Dress",
      "Reformation Women's Cynthia Midi Dress",
      "ASOS Design Women's Wrap Mini Dress Black",
      "ASOS Design Women's Ruched Satin Midi Dress",
      "Anthropologie Women's Floral Midi Dress",
      "Urban Outfitters Women's BDG Boyfriend Jean",
      "Urban Outfitters Women's Corduroy Mini Skirt",
      "Revolve House of Harlow Charly Maxi Dress",
      "Princess Polly Women's Front Tie Blouse White",
      "And Other Stories Women's Belted Blazer Beige",
      "Mango Women's Asymmetric Hem Skirt Ecru",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // SHOES  (80)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Nike", "brand_nike", "cat_shoes", "shoes-footwear", "Shoes & Footwear", 59, 249, IMG.shoes, ["nike", "sneakers", "running"],
    "Nike footwear combines Swoosh heritage with innovative React, ZoomX and Air technology for performance and style.", [
      "Nike Air Force 1 07 White",
      "Nike Air Max 270 Black",
      "Nike Air Max 97 Silver Bullet",
      "Nike Air Jordan 1 Retro High OG Chicago",
      "Nike Air Jordan 4 Retro Military Blue",
      "Nike React Infinity Run Flyknit 4 Black",
      "Nike ZoomX Vaporfly NEXT 3 Pink",
      "Nike Air Zoom Pegasus 41 White",
      "Nike Dunk Low Panda White Black",
      "Nike Dunk High Women's Court Purple",
      "Nike Air Zoom SuperRep 4 Black",
      "Nike Metcon 9 Gray",
      "Nike Free Metcon 6 Black",
      "Nike Blazer Mid 77 Vintage White",
      "Nike Air Presto Black",
      "Nike Air Max Plus TN Black",
      "Nike Air Max 1 Obsidian",
      "Nike Waffle Debut Vintage Green",
      "Nike Court Vision Low White",
      "Nike Air Huarache White",
    ]),

  ...s("Adidas", "brand_adidas", "cat_shoes", "shoes-footwear", "Shoes & Footwear", 49, 229, IMG.shoes, ["adidas", "sneakers", "running"],
    "Adidas footwear innovations like Boost cushioning and Continental rubber soles define streetwear and athletic performance.", [
      "Adidas Ultraboost 24 Core Black",
      "Adidas NMD R1 Core Black",
      "Adidas Stan Smith White Green",
      "Adidas Samba OG White Black",
      "Adidas Gazelle Bold White Core Black",
      "Adidas Superstar White Black",
      "Adidas Forum Low Cloud White",
      "Adidas Handball Spezial Blue",
      "Adidas Adizero Adios Pro 3 White",
      "Adidas Adizero Prime X Strung Black",
      "Adidas SolarBoost 5 Black",
      "Adidas Terrex Swift R3 GORE-TEX Hiking Shoes",
      "Adidas Predator Accuracy FG Football Boots",
      "Adidas X Speedportal FG Football Boots Black",
      "Adidas 4D Fwd Pulse 2 Gray",
      "Adidas Campus 00s Green White",
      "Adidas Response CL White",
      "Adidas Handball Spezial Black",
      "Adidas Tensaur Run Kids Shoes Black",
      "Adidas Grand Court Alpha 2.0 White",
    ]),

  ...s("Puma", "brand_puma", "cat_shoes", "shoes-footwear", "Shoes & Footwear", 44, 199, IMG.shoes, ["puma", "sneakers", "casual"],
    "Puma blends sport performance with lifestyle fashion in footwear from basketball to training and casual.", [
      "Puma Suede Classic XXI White Black",
      "Puma RS-X Reinvention White",
      "Puma Velocity NITRO 3 Black",
      "Puma Deviate NITRO Elite 3 White",
      "Puma Clyde OG Black",
      "Puma Future Rider Play On White",
      "Puma MB.03 LaFranco Black",
      "Puma Slipstream Hi Heritage Cream",
      "Puma Court Ultra White",
      "Puma Mayze Leather White Black",
      "Converse Chuck Taylor All Star Classic High White",
      "Converse Chuck Taylor All Star Classic Low Black",
      "Converse Run Star Hike Platform High Top White",
      "Converse Chuck 70 Hi Vintage White",
      "Converse Pro Leather Platform White",
      "Converse All Star Construct High Top White",
      "Converse Chuck Taylor Colorblock Pink",
      "Converse All Star BB NXT Hi Black",
      "Converse Jack Purcell Low White",
      "Converse Chuck Taylor All Star Move Low",
    ]),

  ...s("New Balance", "brand_newbalance", "cat_shoes", "shoes-footwear", "Shoes & Footwear", 49, 249, IMG.shoes, ["sneakers", "running", "classic"],
    "Trusted footwear from heritage running brands delivering comfort and performance for athletes and everyday wearers.", [
      "New Balance 990v6 Grey",
      "New Balance 574 Gray White",
      "New Balance Fresh Foam X 1080v13 Black",
      "New Balance SuperComp Elite v4 Black",
      "Vans Old Skool Black White",
      "Vans Authentic Black White",
      "Vans Slip-On Black",
      "Skechers DLites Black White",
      "Skechers GOwalk 7 Navy",
      "ASICS Gel-Nimbus 26 Black",
      "ASICS Gel-Kayano 30 White",
      "Brooks Ghost 16 Blue",
      "Brooks Glycerin 21 Black",
      "Salomon Speedcross 6 Red",
      "Hoka Clifton 9 Black",
      "On Cloud 5 White Black",
      "Birkenstock Arizona Soft Footbed Black",
      "Timberland 6-Inch Premium Waterproof Boots Wheat",
      "Dr. Martens 1460 Smooth Leather Boot Black",
      "Steve Madden Irenee Block Heel Sandal Nude",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // BAGS & ACCESSORIES  (50)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Louis Vuitton", "brand_lv", "cat_bags", "bags-accessories", "Bags & Accessories", 299, 3999, IMG.bags, ["luxury", "handbag", "designer"],
    "Luxury handbags crafted from premium materials with iconic monogram patterns and timeless silhouettes.", [
      "Louis Vuitton Neverfull MM Monogram",
      "Louis Vuitton Speedy 30 Monogram",
      "Louis Vuitton Twist PM Epi Leather Black",
      "Gucci Ophidia Small Shoulder Bag Beige",
      "Gucci Jackie 1961 Small Shoulder Bag Camel",
      "Gucci GG Marmont Small Matelasse Bag Black",
      "Coach Tabby Shoulder Bag 26 Black",
      "Coach Jes Crossbody Pebble Leather Black",
      "Coach Dempsey Tote in Signature Canvas Tan",
      "Michael Kors Jet Set Medium Crossbody Black",
      "Michael Kors Hamilton Large Tote Black",
      "Michael Kors Mercer Small Pebbled Tote",
      "Prada Saffiano Lux Small Galleria Bag Black",
      "Prada Re-Edition 2005 Nylon Mini Bag Black",
      "Kate Spade Sam Icon Mini Backpack Black",
      "Kate Spade Knott Pebbled Leather Shoulder Bag",
      "Tory Burch Eleanor Small Convertible Backpack",
      "Tory Burch Miller Soft Pebbled Leather Tote",
      "Ferragamo Hug Reversible Shoulder Bag Black",
      "Valentino Garavani Rockstud Alcove Clutch Black",
      "Mulberry Small Darley Leather Shoulder Bag",
      "Burberry Mini Knight Leather Bag Black",
      "Bottega Veneta Intrecciato Mini Pouch Fondant",
      "Celine Mini Lune Bag Triomphe Tan",
      "Fendi Mini Sunshine Shopper Bag White",
    ]),

  ...s("Herschel", "brand_fjallraven", "cat_bags", "bags-accessories", "Bags & Accessories", 39, 699, IMG.bags, ["backpack", "casual", "travel"],
    "Durable everyday backpacks, travel bags and accessories built for the modern commuter and adventurer.", [
      "Herschel Little America Backpack Black",
      "Herschel Heritage Backpack Tan",
      "JanSport SuperBreak One Backpack Black",
      "JanSport Field Pack Backpack Gray",
      "Fjallraven Kanken Classic Backpack Ox Red",
      "Fjallraven Raven 28 Pack Mountain Blue",
      "Eastpak Padded Pakr Backpack Black",
      "Osprey Farpoint 40 Travel Pack",
      "Osprey Daylite Plus Daypack Black",
      "Thule Lithos Backpack 20L Black",
      "Thule Crossover 2 Backpack 30L Black",
      "Samsonite Freeform Carry-On Spinner Anthracite",
      "Samsonite Classic Leather Business Case Black",
      "Tumi Alpha 3 International Dual Access Carry-On",
      "Away The Carry-On in Aluminum Silver",
      "Away The Large in Coastal Teal",
      "Patagonia Black Hole 32L Backpack Black",
      "The North Face Borealis Backpack Black",
      "Nike Brasilia 9.5 Training Backpack Black",
      "Adidas Defender 4 Duffel Bag Black",
      "Anello Flap Backpack Black",
      "Carhartt WIP Kickflip Backpack Dust",
      "Vans Old Skool Drop V Backpack Black",
      "Dakine 365 Pack 30L Backpack Carbon",
      "Columbia Trek 18L Backpack Black",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // JEWELRY & WATCHES  (30)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Pandora", "brand_pandora", "cat_jewelry", "jewelry-watches", "Jewelry & Watches", 29, 3999, IMG.jewelry, ["jewelry", "luxury", "gift"],
    "Fine jewelry and luxury watches for every occasion — from everyday elegance to milestone celebrations.", [
      "Tiffany and Co T Wire Bracelet White Gold",
      "Tiffany and Co Elsa Peretti Open Heart Pendant",
      "Tiffany and Co Return to Tiffany Oval Tag Pendant",
      "Tiffany and Co Soleste Diamond Ring Platinum",
      "Pandora Moments Snake Chain Bracelet Silver",
      "Pandora Moments Family Tree Charm Silver",
      "Pandora Me Link Chain Bracelet Pink Gold",
      "Pandora Rose Gold Signature Ring",
      "Swarovski Angelic Pendant Necklace White Gold",
      "Swarovski Constella Cluster Ring Rose Gold",
      "Swarovski Tennis Deluxe Necklace White",
      "Mejuri Thin Diamond Band 14k Gold",
      "Mejuri Pave Diamond Huggie Earrings",
      "Mejuri Demi-Fine Link Chain Necklace",
      "Gorjana Chloe Necklace Gold Plated",
      "Kendra Scott Elisa Pendant Necklace Gold White",
      "Fossil Scarlette Multi-function Rose Gold Watch",
      "Fossil Heritage D42 Stainless Steel Watch",
      "Seiko Presage Sharp Edged Automatic Watch",
      "Casio G-Shock GA2100 Black",
      "Citizen Promaster Land Automatic Watch",
      "Orient Bambino Version 6 Automatic Watch",
      "MVMT Boulevard 38mm Leather Strap Watch",
      "Daniel Wellington Classic Sheffield 40mm Watch",
      "Fossil Gen 6 Smartwatch Black",
      "Garmin Forerunner 265 GPS Running Watch",
      "Apple Watch Ultra 2 Titanium 49mm",
      "Apple Watch Series 10 Aluminum 46mm",
      "Samsung Galaxy Watch 7 44mm Graphite",
      "Samsung Galaxy Watch Ultra 47mm Titanium",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // FURNITURE  (60)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("IKEA", "brand_ikea", "cat_furniture", "furniture", "Furniture", 19, 1299, IMG.furniture, ["ikea", "furniture", "scandinavian"],
    "IKEA flat-pack furniture combines Scandinavian design with smart functionality at affordable prices for every room.", [
      "IKEA MALM 6-Drawer Dresser White",
      "IKEA BRIMNES 4-Panel Room Divider White",
      "IKEA HEMNES Day-Bed Frame with 3 Drawers White",
      "IKEA KALLAX Shelf Unit White",
      "IKEA BILLY Bookcase White",
      "IKEA POANG Armchair Birch Veneer",
      "IKEA ALEX Drawer Unit White",
      "IKEA MICKE Desk White",
      "IKEA BEKANT Corner Desk Left White",
      "IKEA SODERHAMN 3-Seat Sofa Finnsta White",
      "IKEA KIVIK 3-Seat Sofa Tibbleby Beige",
      "IKEA BRIMNES Wardrobe with 3 Doors White",
      "IKEA PAX Wardrobe Frame White",
      "IKEA HEMNES 8-Drawer Dresser White",
      "IKEA NORDLI Chest with 9 Drawers White",
      "IKEA TRYSIL Wardrobe Dark Brown",
      "IKEA NOCKEBY 2-Seat Sofa Tallmyra White",
      "IKEA STRANDMON Wing Chair Skiftebo Yellow",
      "IKEA EKEDALEN Extendable Table Dark Brown",
      "IKEA INGATORP Extendable Table White",
      "IKEA JOKKMOKK Table and 4 Chairs Antique",
      "IKEA LISABO Table Ash Veneer",
      "IKEA VEDBO High-Back Armchair Gunnared Light Green",
      "IKEA KARLSTAD 3-Seat Sofa Nacka Gray",
      "IKEA EKTORP 3-Seat Sofa Nordvalla Dark Blue",
      "IKEA VALLENTUNA Modular Sofa Section White",
      "IKEA FLINTAN Office Chair Gray",
      "IKEA MARKUS Office Chair Vissle Dark Gray",
      "IKEA GLADOM Tray Table Black",
      "IKEA HEKTAR Floor Lamp Dark Gray",
    ]),

  ...s("West Elm", "brand_westelm", "cat_furniture", "furniture", "Furniture", 99, 3499, IMG.furniture, ["modern", "furniture", "sustainable"],
    "Contemporary sustainable furniture designed for modern homes — from accent chairs to statement dining tables.", [
      "West Elm Andes Mid-Century Sofa Linen Weave",
      "West Elm Drake Mid-Century Coffee Table Walnut",
      "West Elm Portside Outdoor Dining Table Gray",
      "West Elm Industrial Storage Desk Antique Bronze",
      "West Elm Slope Dining Chair Upholstered White",
      "Pottery Barn Bedford Corner Desk Set White",
      "Pottery Barn Classic Canvas Tufted Ottoman",
      "Pottery Barn Comfort Roll Arm Sofa",
      "Pottery Barn Classic Upholstered Bed White",
      "Pottery Barn Sadie Bookcase Antique White",
      "Article Ceni Dining Chair Beige",
      "Article Timber Mid-Century Coffee Table",
      "Article Nera 3-Piece Sectional Sofa Charcoal",
      "Casper Wave Hybrid Mattress King",
      "Purple Plus Mattress Queen",
      "Saatva Classic Innerspring Mattress King",
      "Nectar Premier Copper Queen Mattress",
      "Herman Miller Aeron Chair Graphite",
      "Herman Miller Mirra 2 Chair Black",
      "Steelcase Leap Chair Black",
      "Branch Ergonomic Chair Black",
      "FlexiSpot E7 Pro Plus Standing Desk White",
      "Flexispot Comhar Standing Desk Walnut",
      "Autonomous Desk Eureka Electric White",
      "BDI Corridor Media Console Sliding Doors",
      "Wayfair Kelly Clarkson Home Barrel Chair Gray",
      "Wayfair Latitude Run L-Shaped Desk White",
      "Wayfair Three Posts Twin Over Full Bunk Bed",
      "Restoration Hardware Cloud Sofa Performance",
      "Restoration Hardware Belgian Slope Arm Chair",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // KITCHEN & DINING  (50)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("KitchenAid", "brand_kitchenaid", "cat_kitchen", "kitchen-dining", "Kitchen & Dining", 49, 799, IMG.kitchen, ["kitchen", "appliance", "cooking"],
    "KitchenAid's iconic stand mixers, food processors and appliances are the cornerstone of culinary creativity.", [
      "KitchenAid Artisan 5-Qt Stand Mixer Empire Red",
      "KitchenAid Artisan 5-Qt Stand Mixer White",
      "KitchenAid Professional 600 Series 6-Qt Mixer",
      "KitchenAid 13-Cup Food Processor Contour Silver",
      "KitchenAid 3.5-Qt Mini Food Chopper",
      "Instant Pot Duo 7-in-1 Pressure Cooker 6Qt",
      "Instant Pot Pro 10-in-1 Pressure Cooker 6Qt",
      "Instant Pot Duo Crisp 11-in-1 Air Fryer 6Qt",
      "Vitamix 5200 Blender Black",
      "Vitamix A3500 Ascent Series Brushed Stainless",
      "Vitamix Professional Series 750 Brushed Stainless",
      "Breville Barista Express Espresso Machine Black",
      "Breville Oracle Touch Espresso Machine Black",
      "Breville Super Q Blender Brushed Stainless",
      "Cuisinart 14-Cup Food Processor White",
      "Cuisinart SmartStick Hand Blender Stainless",
      "Ninja Professional Plus Kitchen System 72oz",
      "Ninja Foodi 12-in-1 6.5-Qt Air Fryer Oven",
      "Keurig K-Elite Single Serve Coffee Maker Gray",
      "Nespresso Vertuo Next Bundle Black Chrome",
      "De Longhi Stilosa Espresso Machine Black",
      "Zwilling Twin Pro S 8-Piece Knife Block Set",
      "Wusthof Classic 7-Piece Knife Block Set",
      "Global G-2 8-Inch Chef Knife",
      "Lodge Pre-Seasoned Cast Iron Skillet 12-Inch",
    ]),

  ...s("Le Creuset", "brand_lecreuset", "cat_kitchen", "kitchen-dining", "Kitchen & Dining", 19, 449, IMG.kitchen, ["cookware", "kitchen", "bakeware"],
    "Premium cookware, coffee brewing equipment and kitchen tools for the passionate home cook and entertainer.", [
      "Le Creuset Enameled Cast Iron Dutch Oven 5.5Qt Cerise",
      "Le Creuset Stainless Steel Saucepan 3-Ply 3Qt",
      "Staub Round Cocotte 5.5Qt Black Matte",
      "All-Clad D3 Stainless Steel 10-Inch Fry Pan",
      "OXO Good Grips 11-Piece Cookware Set Stainless",
      "OXO Good Grips Pop Container 6-Piece Set",
      "OXO Brew Pour-Over Coffee Maker with Water Tank",
      "Chemex 6-Cup Pour-Over Glass Coffee Maker",
      "Fellow Stagg EKG Electric Gooseneck Kettle Black",
      "Hario V60 Ceramic Coffee Dripper White",
      "Philips Airfryer XXL 3-lb HD9650 Black",
      "Cosori Air Fryer 5.8-Qt Max XL Black",
      "Anova Precision Cooker Pro Sous Vide",
      "Breville Smart Oven Air Fryer Pro 22L",
      "Hamilton Beach Breakfast Sandwich Maker Silver",
      "Cuisinart 2-Slice Stainless Steel Toaster",
      "Smeg 2-Slice Toaster Pastel Green",
      "Smeg Coffee Grinder Pastel Pink",
      "Dyson V15 Detect Absolute Cordless Vacuum",
      "iRobot Roomba s9 Plus Self-Emptying Robot Vacuum",
      "Shark IQ Robot Vacuum Black",
      "Bissell CrossWave Pet Pro All-in-One Wet Dry",
      "Dyson Purifier Hot Plus Cool Fan Black",
      "OXO Good Grips Mixing Bowl Set 3-Piece",
      "Microplane Premium Zester Grater",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // BEDDING & BATH  (30)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Casper", "brand_westelm", "cat_bedding", "bedding-bath", "Bedding & Bath", 19, 1299, IMG.bedding, ["bedding", "sleep", "comfort"],
    "Premium bedding, mattresses and bath essentials designed for the best sleep and bath experience every night.", [
      "Casper Original Pillow Standard White",
      "Casper Original Pillow Queen White",
      "Purple Harmony Pillow Standard Purple",
      "Parachute Classic European Linen Duvet Cover",
      "Parachute Classic Linen Sheet Set King",
      "Brooklinen Classic Hardcore Bundle Sheets Gray",
      "Brooklinen Luxe Sateen Duvet Cover White",
      "Buffy Cloud Comforter Queen",
      "Buffy Breeze Comforter Twin White",
      "Cozy Earth Bamboo Sheet Set Queen Gray",
      "Cozy Earth 100% Bamboo Duvet Cover White",
      "Boll and Branch Signature Hemmed Sheet Set Ivory",
      "Boll and Branch Pebble Waffle Blanket Gray",
      "Saatva Organic Cotton Sateen Sheet Set Queen",
      "Saatva Luxury Mattress Pad Queen White",
      "Coyuchi Organic Cotton Muslin Duvet Cover",
      "IKEA MALM Bed Frame with High Headboard White",
      "IKEA HEMNES Bed Frame with Headboard White",
      "Zinus Dachelle Upholstered Platform Bed Gray",
      "Zinus SmartBase Metal Bed Frame Queen",
      "Nectar Adjustable Base Queen Smart Bed Frame",
      "Avocado Green Mattress Queen Organic",
      "WinkBed King Luxury Innerspring Mattress",
      "DreamCloud Premier Rest Luxury Hybrid Mattress",
      "Tempur-Pedic TEMPUR-ProAdapt Queen Mattress",
      "Purple Restore Hybrid Premier King Mattress",
      "Sleep Number 360 i8 Smart Bed Queen",
      "Tuft and Needle Original Foam Mattress Full",
      "Leesa Legend Cooling Hybrid Mattress Queen",
      "Helix Midnight Luxe Hybrid Mattress King",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // HOME DECOR  (30)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("West Elm", "brand_westelm", "cat_decor", "home-decor", "Home Decor", 9, 499, IMG.decor, ["decor", "home", "design"],
    "Curated home decor from sculptural vases to statement lighting that elevates every corner of your living space.", [
      "West Elm Solid Ribbed Decorative Vase Matte Black",
      "West Elm Brass Arc Floor Lamp",
      "West Elm Oversized Rectangle Mirror",
      "Pottery Barn Rustic Wood Frame Gallery Wall Set",
      "Pottery Barn Felted Wool Throw Blanket Gray",
      "IKEA FEJKA Artificial Plant in Pot",
      "IKEA STENHOJDEN Table Lamp Beige",
      "World Market Hamilton Metal Bar Cart Black",
      "Target Studio McGee Sculptural Vase",
      "H&M Home Linen Cushion Cover Gray",
      "H&M Home Cotton Knit Throw Beige",
      "Anthropologie Sculptural Ceramic Vase White",
      "Anthropologie Woven Cotton Tassel Throw Blanket",
      "Urban Outfitters UO Home Canvas Wall Art",
      "Wayfair Zipcode Design Area Rug 5x7 Gray",
      "Amazon Basics Full-Motion TV Wall Mount",
      "BenQ ScreenBar Halo Monitor Light Black",
      "Elgato Key Light Studio Light",
      "Govee Envisual TV Backlight T2 RGBIC",
      "Philips Hue Lightstrip Plus 2m White",
      "Nanoleaf Shapes Hexagon Smarter Kit",
      "Lutron Caseta Wireless Smart Dimmer Switch",
      "LIFX A19 Smart LED Light Bulb",
      "GE CYNC Smart LED Light Bulbs 4-Pack",
      "Wyze Cam v3 Indoor Outdoor Smart Camera",
      "Arlo Essential 2K Wireless Security Camera",
      "Reolink RLC-810A 4K PoE Security Camera",
      "Umbra Trigg Floating Wall Shelf White",
      "CB2 Fili Brass Candleholder Set",
      "Crate and Barrel Orb Pillar Candle Holder",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // SKINCARE  (50)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("La Mer", "brand_clinique", "cat_skincare", "skincare", "Skincare", 29, 399, IMG.skincare, ["skincare", "luxury", "moisturizer"],
    "Premium skincare formulated with clinically proven actives — serums, moisturizers and treatments for every skin type.", [
      "La Mer Moisturizing Cream 60ml",
      "La Mer The Eye Concentrate 15ml",
      "La Mer Regenerating Serum Advanced 50ml",
      "SkinCeuticals C E Ferulic Serum 30ml",
      "SkinCeuticals Triple Lipid Restore 2-4-2 48ml",
      "Clinique Dramatically Different Moisturizing Lotion 125ml",
      "Clinique Moisture Surge 100-Hour Hydrator 75ml",
      "Estee Lauder Advanced Night Repair Serum",
      "Estee Lauder Revitalizing Supreme Plus Moisturizer 75ml",
      "Origins GinZing Refreshing Eye Cream 15ml",
      "Tatcha The Water Cream 60ml",
      "Tatcha The Essence Plumping Skin Softener",
      "Sunday Riley Good Genes Lactic Acid Treatment",
      "Drunk Elephant Protini Polypeptide Cream 50ml",
      "Drunk Elephant TLC Framboos Glycolic Night Serum",
      "Paula's Choice SKIN PERFECTING 2% BHA Liquid",
      "COSRX Advanced Snail 96 Mucin Power Essence",
      "Laneige Water Sleeping Mask 70ml",
      "Innisfree Green Tea Seed Hyaluronic Serum",
      "Sulwhasoo First Care Activating Serum 60ml",
      "SK-II Facial Treatment Essence 230ml",
      "NARS Pure Radiant Tinted Moisturizer SPF30",
      "Charlotte Tilbury Magic Cream Moisturiser 50ml",
      "Elemis Pro-Collagen Marine Cream 50ml",
      "Sisley Black Rose Cream Mask",
    ]),

  ...s("CeraVe", "brand_cerave", "cat_skincare", "skincare", "Skincare", 9, 49, IMG.skincare, ["skincare", "dermatologist", "affordable"],
    "Dermatologist-recommended skincare with ceramides and essential ingredients for healthy skin barrier restoration.", [
      "CeraVe Daily Moisturizing Lotion 8oz",
      "CeraVe Hydrating Facial Cleanser 12oz",
      "CeraVe Healing Ointment 5oz",
      "CeraVe Skin Renewing Vitamin C Serum 1oz",
      "La Roche-Posay Toleriane Double Repair Moisturizer",
      "La Roche-Posay Anthelios Melt-in Milk SPF100",
      "La Roche-Posay Effaclar Medicated Gel Cleanser",
      "L'Oreal Paris Revitalift 1.5% Hyaluronic Acid Serum",
      "L'Oreal Paris Age Perfect Rosy Tone Moisturizer",
      "Neutrogena Hydro Boost Water Gel Moisturizer",
      "Neutrogena Rapid Wrinkle Repair Retinol Serum",
      "Neutrogena Ultra Sheer Dry-Touch Sunscreen SPF70",
      "Olay Regenerist Micro-Sculpting Cream Moisturizer",
      "Olay Vitamin C Peptide 24 Brightening Eye Cream",
      "Aveeno Daily Moisturizing Lotion",
      "Aveeno Calm and Restore Triple Oat Nourishing Lotion",
      "Vanicream Moisturizing Skin Cream",
      "First Aid Beauty Ultra Repair Cream",
      "Thayers Witch Hazel Toner Original",
      "Mario Badescu Drying Lotion",
      "Kiehl's Ultra Facial Cream",
      "Origins Clear Improvement Active Charcoal Mask",
      "Freeman Sweet Tea and Lemon Sugar Facial Scrub",
      "e.l.f. Holy Hydration Face Cream",
      "Versed Weekend Glow Daily Brightening Solution",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // MAKEUP  (50)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("MAC", "brand_mac", "cat_makeup", "makeup-cosmetics", "Makeup & Cosmetics", 19, 129, IMG.makeup, ["makeup", "professional", "cosmetics"],
    "Professional-quality makeup trusted by artists worldwide — foundations, lipsticks, eyeshadows and more.", [
      "MAC Prep and Prime Fix Plus Setting Spray",
      "MAC Studio Fix Fluid SPF15 Full Coverage Foundation",
      "MAC Mineralize Skinfinish Powder Natural Medium",
      "MAC Strobe Cream Pinklite",
      "MAC Lip Colour Chili",
      "Charlotte Tilbury Airbrush Flawless Foundation",
      "Charlotte Tilbury Hollywood Flawless Filter",
      "Charlotte Tilbury Pillow Talk Lipstick",
      "Fenty Beauty Pro Filtr Soft Matte Foundation",
      "Fenty Beauty Galaxy Palette Kaleidoscope",
      "Fenty Beauty Stunna Lip Paint Uncensored Red",
      "Urban Decay Naked3 Eyeshadow Palette",
      "Urban Decay All Nighter Setting Spray",
      "Urban Decay 24-7 Glide-On Eye Pencil Black",
      "NARS Radiant Creamy Concealer Light",
      "NARS Soft Matte Complete Foundation",
      "NARS Orgasm Blush",
      "Too Faced Better Than Sex Mascara",
      "Benefit Cosmetics BADgal BANG Mascara",
      "Benefit POREfessional Face Primer",
      "Anastasia Beverly Hills Dipbrow Pomade Dark Brown",
      "Anastasia Beverly Hills Modern Renaissance Palette",
      "Hourglass Ambient Lighting Powder",
      "Pat McGrath Labs MatteTrance Lipstick Elson",
      "Rare Beauty Soft Pinch Liquid Blush",
    ]),

  ...s("NYX", "brand_nyx", "cat_makeup", "makeup-cosmetics", "Makeup & Cosmetics", 7, 39, IMG.makeup, ["makeup", "affordable", "vegan"],
    "High-quality, cruelty-free makeup at drugstore prices — bold colors, excellent formulas, inclusive shade ranges.", [
      "NYX Professional Makeup Epic Ink Liner Black",
      "NYX Professional Makeup Setting Spray",
      "NYX Professional Makeup Lip Lingerie Lipstick",
      "Maybelline Instant Age Rewind Concealer Light",
      "Maybelline Fit Me Matte Poreless Foundation",
      "Maybelline Sky High Mascara Black",
      "L'Oreal Paris Infallible Full Wear Concealer",
      "L'Oreal Paris True Match Super-Blendable Foundation",
      "L'Oreal Paris Voluminous Original Mascara Black",
      "Revlon ColorStay Foundation Combination Normal",
      "Revlon PhotoReady Candid Foundation",
      "e.l.f. Camo Concealer Foundation Light",
      "e.l.f. Poreless Putty Primer",
      "e.l.f. 16HR Camo Concealer",
      "Milani Conceal and Perfect Concealer Medium Beige",
      "Wet n Wild Photofocus Foundation",
      "Physicians Formula Butter Bronzer Light Bronzer",
      "Morphe 350 Shimmer Nature Eyeshadow Palette",
      "BH Cosmetics Studio Pro Neutrals Palette",
      "ColourPop No Filter Concealer Stick",
      "Makeup Revolution Fast Base Foundation",
      "Essence Lash Princess False Lash Mascara",
      "Catrice Feather Effect Mascara",
      "ELF Shadow Putty Eyeshadow Primer",
      "Covergirl Clean Fresh Yummy Gloss Lip Gloss",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // FITNESS  (40)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("Garmin", "brand_garmin", "cat_fitness", "fitness-exercise", "Fitness & Exercise", 19, 1199, IMG.fitness, ["fitness", "sports", "tracking"],
    "Performance fitness gear and GPS smartwatches for runners, cyclists, swimmers and multi-sport athletes.", [
      "Garmin Forerunner 265 GPS Running Smartwatch",
      "Garmin Forerunner 965 GPS Triathlon Smartwatch",
      "Garmin Fenix 8 Solar Multisport GPS Watch",
      "Garmin Venu 3 GPS Smartwatch",
      "Garmin Vivomove Trend Hybrid Watch",
      "Garmin Edge 840 GPS Cycling Computer",
      "Garmin HRM-Pro Plus Heart Rate Monitor",
      "Garmin Forerunner 255 GPS Running Watch",
      "Garmin vivoactive 5 GPS Smartwatch",
      "Garmin Instinct 2 Solar Rugged GPS Watch",
      "Nike Training Dumbbell Set 5lbs Pair",
      "Nike Training Dumbbell Set 10lbs Pair",
      "Nike Training Dumbbell Set 20lbs Pair",
      "Nike Yoga 4mm Training Mat",
      "Nike Training Yoga Block",
      "Nike Precision Pool Goggle Clear",
      "Nike Brasilia Medium Training Duffel Bag",
      "Nike Speed Rope Training Jump Rope",
      "Nike Resistance Band Set",
      "Nike Agility Ladder Training Kit",
    ]),

  ...s("Under Armour", "brand_ua", "cat_fitness", "fitness-exercise", "Fitness & Exercise", 29, 199, IMG.fitness, ["fitness", "performance", "training"],
    "Science-backed performance gear and equipment to push your training further with UA HOVR and HeatGear technology.", [
      "Under Armour HeatGear Armour Compression Leggings",
      "Under Armour UA HOVR Machina 3 Running Shoes",
      "Under Armour UA HOVR Phantom 3 Running Shoes",
      "Under Armour Rival Terry Joggers",
      "Under Armour Project Rock Bench Press",
      "Under Armour Project Rock 5 Training Shoes",
      "Decathlon Domyos Weight Bench",
      "Decathlon Domyos 20kg Dumbbell Set",
      "Decathlon Domyos Yoga Mat 5mm Blue",
      "Decathlon Domyos Jump Rope Speed Black",
      "Decathlon Domyos Resistance Bands Set",
      "Decathlon Domyos Pull-Up Bar for Doorway",
      "Decathlon Btwin 500 Fitness Bike",
      "Decathlon Domyos Adjustable Dumbbell 24kg",
      "Wahoo KICKR Core Smart Trainer",
      "Peloton Bike Plus Indoor Stationary Bike",
      "NordicTrack Treadmill T Series 9.5S",
      "Bowflex BXT216 Treadmill",
      "Sunny Health Fitness Magnetic Rowing Machine",
      "TRX All-in-One Suspension Training System",
    ]),

  // ════════════════════════════════════════════════════════════════════════════
  // GAMING  (30)
  // ════════════════════════════════════════════════════════════════════════════

  ...s("PlayStation", "brand_playstation", "cat_console", "consoles-games", "Consoles & Games", 49, 699, IMG.gaming, ["gaming", "console", "playstation"],
    "PlayStation 5 delivers next-generation gaming with lightning-fast SSD, DualSense haptics and exclusive titles.", [
      "PlayStation 5 Console Disc Edition",
      "PlayStation 5 Console Digital Edition",
      "PlayStation 5 Slim Console Disc Edition",
      "DualSense Wireless Controller Midnight Black",
      "DualSense Wireless Controller Cobalt Blue",
      "DualSense Edge Wireless Controller",
      "PlayStation 5 Media Remote",
      "Nintendo Switch OLED Model White Set",
      "Nintendo Switch OLED Model Splatoon 3 Edition",
      "Nintendo Switch Lite Turquoise",
      "Nintendo Switch Lite Gray",
      "Nintendo Joy-Con Pair Neon Red Blue",
      "Nintendo Switch Pro Controller",
      "Nintendo eShop Gift Card 50 USD",
      "Nintendo Switch Sports Game",
    ]),

  ...s("Xbox", "brand_xbox", "cat_pc_gaming", "pc-gaming", "PC Gaming", 39, 599, IMG.gaming, ["gaming", "pc", "peripherals"],
    "Xbox consoles, controllers and PC gaming peripherals from Razer, Corsair and Logitech for competitive gaming.", [
      "Xbox Series X 1TB Console",
      "Xbox Series S 512GB Console White",
      "Xbox Wireless Controller Carbon Black",
      "Xbox Wireless Controller Robot White",
      "Xbox Wireless Controller Electric Volt",
      "Xbox Game Pass Ultimate 3-Month Membership",
      "Razer BlackShark V2 Pro Wireless Headset Black",
      "Razer DeathAdder V3 Pro Wireless Mouse",
      "Razer BlackWidow V4 Mechanical Gaming Keyboard",
      "Razer Huntsman V3 Pro Analog Gaming Keyboard",
      "Razer Seiren V3 X USB Microphone Black",
      "Corsair K70 RGB MK2 Mechanical Keyboard",
      "Corsair HS80 Max Wireless Gaming Headset",
      "SteelSeries Arctis Nova Pro Wireless Headset",
      "Logitech G Pro X Superlight 2 Wireless Mouse",
    ]),
];

// Slug lookup map for fast product-by-slug queries
export const mockProductBySlug = new Map<string, MockProduct>(
  mockProducts.map((p) => [p.slug ?? "", p])
);
