import type { MockBrand } from "./types";

export const mockBrands: MockBrand[] = [
  {
    id: "br_1",
    name: "SoundMax",
    slug: "soundmax",
    category: "Audio",
    description: "Premium audio gear focused on clarity and comfort.",
    productCount: 14,
    featured: true,
    accent: "from-amber-500/20 via-orange-500/10 to-transparent",
  },
  {
    id: "br_2",
    name: "TechBand",
    slug: "techband",
    category: "Wearables",
    description: "Smart accessories for everyday fitness and productivity.",
    productCount: 9,
    featured: true,
    accent: "from-sky-500/20 via-cyan-500/10 to-transparent",
  },
  {
    id: "br_3",
    name: "StorageX",
    slug: "storagex",
    category: "Storage",
    description: "Portable storage and creator-grade backup hardware.",
    productCount: 8,
    featured: false,
    accent: "from-violet-500/20 via-fuchsia-500/10 to-transparent",
  },
  {
    id: "br_4",
    name: "ClickMaster",
    slug: "clickmaster",
    category: "Peripherals",
    description: "Desk gear and precision tools for high-output workflows.",
    productCount: 11,
    featured: false,
    accent: "from-rose-500/20 via-pink-500/10 to-transparent",
  },
  {
    id: "br_5",
    name: "StudioKit",
    slug: "studiokit",
    category: "Accessories",
    description: "Creator accessories and lighting kits for better content.",
    productCount: 6,
    featured: false,
    accent: "from-emerald-500/20 via-lime-500/10 to-transparent",
  },
];