export type MockCatalogCategory = {
  id: string;
  name: string;
  slug: string;
  description: string;
  featured: boolean;
  tone: string;
  brands: string[];
  tags: string[];
  image: string;
  products: Array<{
    name: string;
    price: number;
    color: string;
    material: string;
    dimensions: string;
    weight: string;
  }>;
};

const product = (
  name: string,
  price: number,
  color: string,
  material: string,
  dimensions: string,
  weight: string,
) => ({ name, price, color, material, dimensions, weight });

const allMockCatalogCategories: MockCatalogCategory[] = [
  {
    id: "cat_audio",
    name: "Audio",
    slug: "audio",
    description: "Headphones, earbuds, speakers, and microphones tuned for work, travel, and home listening.",
    featured: true,
    tone: "from-sky-500/20 via-cyan-500/10 to-transparent",
    brands: ["Sony", "Bose", "JBL", "Sennheiser", "Marshall"],
    tags: ["wireless", "noise-cancelling", "portable", "studio"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
    products: [
      product("Sony WH-1000XM5 Wireless Headphones", 279.99, "Midnight black", "Aluminum, vegan leather", "7.8 x 2.6 x 10 in", "0.55 lb"),
      product("Bose QuietComfort Ultra Earbuds", 249.99, "Smoke white", "Polycarbonate, silicone", "2.6 x 1.8 x 1.2 in", "0.16 lb"),
      product("JBL Charge 5 Portable Speaker", 149.95, "Ocean blue", "Recycled fabric, rubber", "8.7 x 3.8 x 3.7 in", "2.1 lb"),
      product("Sennheiser Momentum 4 Wireless", 299.95, "Graphite", "Steel, memory foam", "7.1 x 1.8 x 7.7 in", "0.65 lb"),
      product("Marshall Emberton II Speaker", 169.99, "Black brass", "Silicone, metal grille", "6.3 x 3.0 x 2.7 in", "1.5 lb"),
      product("Audio-Technica AT2020USB-X Microphone", 149.0, "Matte black", "Metal chassis", "5.6 x 2.0 x 2.0 in", "0.82 lb"),
      product("Shure MV7 Podcast Microphone", 249.0, "Black", "Metal, foam windscreen", "6.0 x 3.5 x 3.0 in", "1.2 lb"),
      product("Anker Soundcore Space One", 99.99, "Latte cream", "ABS, protein leather", "7.6 x 3.3 x 8.1 in", "0.58 lb"),
      product("Sonos Roam SL Compact Speaker", 159.0, "Lunar white", "Polycarbonate", "6.6 x 2.4 x 2.4 in", "0.95 lb"),
      product("Rode Wireless ME Lavalier Kit", 149.0, "Black", "ABS, clip mount", "1.7 x 1.8 x 0.7 in", "0.14 lb"),
    ],
  },
  {
    id: "cat_wearables",
    name: "Wearables",
    slug: "wearables",
    description: "Smartwatches, trackers, rings, and straps for fitness, productivity, and wellness.",
    featured: true,
    tone: "from-emerald-500/20 via-lime-500/10 to-transparent",
    brands: ["Apple", "Samsung", "Garmin", "Fitbit", "Oura"],
    tags: ["fitness", "health", "gps", "water-resistant"],
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop",
    products: [
      product("Apple Watch Series 9 GPS 45mm", 399.99, "Midnight", "Aluminum, fluoroelastomer", "45 mm case", "0.09 lb"),
      product("Samsung Galaxy Watch6 Classic 47mm", 369.99, "Silver", "Stainless steel", "47 mm case", "0.13 lb"),
      product("Garmin Venu 3 Fitness Smartwatch", 449.99, "Slate", "Fiber-reinforced polymer", "45 mm case", "0.10 lb"),
      product("Fitbit Charge 6 Activity Tracker", 159.95, "Porcelain", "Aluminum, silicone", "1.5 x 0.7 in", "0.07 lb"),
      product("Oura Ring Gen3 Heritage", 299.0, "Brushed titanium", "Titanium", "Size 6-13", "0.01 lb"),
      product("Amazfit Balance Smartwatch", 229.99, "Sunset grey", "Aluminum alloy", "46 mm case", "0.08 lb"),
      product("Polar H10 Heart Rate Sensor", 89.95, "Black", "Textile strap, sensor pod", "Adjustable strap", "0.13 lb"),
      product("Whoop 4.0 SuperKnit Band", 239.0, "Onyx", "Knit nylon", "Adjustable", "0.05 lb"),
      product("Apple Sport Loop 45mm Band", 49.0, "Starlight", "Woven nylon", "45 mm", "0.03 lb"),
      product("Garmin Forerunner 265 Running Watch", 449.99, "Aqua black", "Polymer, silicone", "46 mm case", "0.10 lb"),
    ],
  },
  {
    id: "cat_storage",
    name: "Storage",
    slug: "storage",
    description: "Portable SSDs, memory cards, hard drives, and NAS-ready drives for creators and teams.",
    featured: false,
    tone: "from-violet-500/20 via-fuchsia-500/10 to-transparent",
    brands: ["Samsung", "SanDisk", "Seagate", "Western Digital", "Lexar"],
    tags: ["ssd", "backup", "creator", "high-speed"],
    image: "https://images.unsplash.com/photo-1531492898419-3a9aa15ebbd0?w=600&h=600&fit=crop",
    products: [
      product("Samsung T7 Shield Portable SSD 2TB", 179.99, "Beige", "Rubberized aluminum", "3.5 x 2.3 x 0.5 in", "0.22 lb"),
      product("SanDisk Extreme Pro Portable SSD 4TB", 349.99, "Black orange", "Forged aluminum", "4.3 x 2.3 x 0.4 in", "0.17 lb"),
      product("Seagate One Touch HDD 5TB", 134.99, "Space grey", "Brushed aluminum", "4.5 x 3.1 x 0.8 in", "0.59 lb"),
      product("WD Black SN850X NVMe SSD 2TB", 159.99, "Black", "PCB, heatsink", "3.2 x 0.9 x 0.1 in", "0.02 lb"),
      product("Lexar Professional 2000x SDXC 128GB", 119.99, "Black gold", "Plastic", "SD card", "0.01 lb"),
      product("Kingston Canvas React Plus 256GB", 89.99, "Black", "Plastic", "SD card", "0.01 lb"),
      product("Crucial X9 Pro Portable SSD 1TB", 109.99, "Charcoal", "Anodized aluminum", "2.6 x 2.0 x 0.4 in", "0.08 lb"),
      product("Samsung Pro Plus microSD 512GB", 44.99, "Blue", "Plastic", "microSD", "0.01 lb"),
      product("WD Red Plus NAS Drive 8TB", 179.99, "Red", "Metal enclosure", "3.5 in drive", "1.6 lb"),
      product("LaCie Rugged Mini HDD 4TB", 159.99, "Orange silver", "Aluminum, rubber", "5.3 x 3.4 x 1.0 in", "0.75 lb"),
    ],
  },
  {
    id: "cat_peripherals",
    name: "Peripherals",
    slug: "peripherals",
    description: "Keyboards, mice, webcams, hubs, and desk tools for reliable daily productivity.",
    featured: false,
    tone: "from-amber-500/20 via-orange-500/10 to-transparent",
    brands: ["Logitech", "Keychron", "Razer", "Elgato", "Anker"],
    tags: ["desk-setup", "usb-c", "ergonomic", "productivity"],
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=600&h=600&fit=crop",
    products: [
      product("Logitech MX Master 3S Mouse", 99.99, "Graphite", "Plastic, metal wheel", "4.9 x 3.3 x 2.0 in", "0.31 lb"),
      product("Keychron K8 Pro Wireless Keyboard", 109.99, "Carbon black", "Aluminum, PBT keycaps", "14.1 x 5.0 x 1.6 in", "2.4 lb"),
      product("Razer Basilisk V3 Pro Mouse", 159.99, "Black", "Textured polymer", "5.1 x 2.9 x 1.7 in", "0.25 lb"),
      product("Logitech Brio 4K Webcam", 199.99, "Black", "Plastic, glass lens", "4.0 x 1.1 x 1.1 in", "0.36 lb"),
      product("Elgato Stream Deck MK.2", 149.99, "Black", "Plastic, LCD keys", "4.6 x 3.3 x 1.0 in", "0.32 lb"),
      product("Anker 565 USB-C Hub 11-in-1", 79.99, "Space grey", "Aluminum", "5.4 x 2.1 x 0.6 in", "0.22 lb"),
      product("Logitech MX Keys S Keyboard", 109.99, "Pale grey", "Low-carbon aluminum", "16.9 x 5.2 x 0.8 in", "1.8 lb"),
      product("CalDigit Thunderbolt 4 Element Hub", 249.99, "Silver", "Aluminum", "4.5 x 2.8 x 0.7 in", "0.40 lb"),
      product("Wacom Intuos Bluetooth Tablet", 99.95, "Black", "Plastic, textured surface", "7.9 x 6.3 x 0.4 in", "0.55 lb"),
      product("BenQ ScreenBar Halo Monitor Light", 179.0, "Matte black", "Aluminum, polycarbonate", "19.7 x 3.8 x 3.8 in", "1.7 lb"),
    ],
  },
  {
    id: "cat_accessories",
    name: "Accessories",
    slug: "accessories",
    description: "Cables, chargers, mounts, sleeves, and practical add-ons that lift average order value.",
    featured: false,
    tone: "from-rose-500/20 via-pink-500/10 to-transparent",
    brands: ["Anker", "Belkin", "Peak Design", "Nomad", "Twelve South"],
    tags: ["charging", "travel", "daily-carry", "bundle"],
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=600&fit=crop",
    products: [
      product("Anker 737 GaNPrime Charger 120W", 89.99, "Black", "Fire-resistant plastic", "3.1 x 1.7 x 1.3 in", "0.42 lb"),
      product("Belkin BoostCharge Pro 3-in-1 Stand", 149.99, "White", "Metal, soft-touch plastic", "5.3 x 4.1 x 5.4 in", "1.2 lb"),
      product("Peak Design Mobile Tripod", 79.95, "Charcoal", "Machined aluminum", "3.0 x 2.2 x 0.3 in", "0.17 lb"),
      product("Nomad USB-C Kevlar Cable 1.5m", 39.95, "Black", "Kevlar, metal tips", "5 ft", "0.13 lb"),
      product("Twelve South Curve Flex Stand", 79.99, "Matte white", "Aluminum, silicone", "10.3 x 8.8 x 1.1 in", "1.6 lb"),
      product("Native Union Stow Lite Sleeve 14in", 49.99, "Sage", "Recycled polyester", "13.8 x 9.8 x 0.8 in", "0.50 lb"),
      product("Mophie Powerstation 10K", 49.95, "Black", "Plastic", "5.6 x 2.8 x 0.6 in", "0.50 lb"),
      product("Satechi Aluminum Laptop Riser", 44.99, "Silver", "Aluminum", "9.5 x 9.5 x 3.2 in", "1.1 lb"),
      product("Moment MagSafe Car Vent Mount", 39.99, "Black", "Polycarbonate, magnets", "2.7 x 2.7 x 1.5 in", "0.18 lb"),
      product("Ugreen Nexode 200W Desktop Charger", 199.99, "Space grey", "Plastic, gallium nitride", "4.0 x 4.0 x 1.3 in", "1.1 lb"),
    ],
  },
  {
    id: "cat_laptops",
    name: "Laptops",
    slug: "laptops",
    description: "Portable computers for students, developers, creators, and business teams.",
    featured: true,
    tone: "from-blue-500/20 via-indigo-500/10 to-transparent",
    brands: ["Apple", "Dell", "Lenovo", "ASUS", "HP"],
    tags: ["workstation", "ultrabook", "creator", "student"],
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&h=600&fit=crop",
    products: [
      product("Apple MacBook Air 13 M3 512GB", 1299.0, "Starlight", "Aluminum", "11.97 x 8.46 x 0.44 in", "2.7 lb"),
      product("Dell XPS 14 OLED Laptop", 1699.99, "Platinum", "CNC aluminum", "12.6 x 8.5 x 0.7 in", "3.7 lb"),
      product("Lenovo ThinkPad X1 Carbon Gen 12", 1849.0, "Black", "Carbon fiber, magnesium", "12.3 x 8.5 x 0.6 in", "2.4 lb"),
      product("ASUS Zenbook 14 OLED", 1099.99, "Ponder blue", "Aluminum", "12.3 x 8.7 x 0.6 in", "2.8 lb"),
      product("HP Spectre x360 14", 1499.99, "Nightfall black", "Aluminum", "12.4 x 8.7 x 0.7 in", "3.2 lb"),
      product("Microsoft Surface Laptop 6 15in", 1599.99, "Sapphire", "Aluminum, Alcantara", "13.4 x 9.6 x 0.7 in", "3.7 lb"),
      product("Acer Swift Go 14 Intel Evo", 899.99, "Mist green", "Aluminum", "12.3 x 8.6 x 0.6 in", "2.8 lb"),
      product("Razer Blade 14 Gaming Laptop", 2399.99, "Mercury", "CNC aluminum", "12.2 x 8.9 x 0.7 in", "4.1 lb"),
      product("LG Gram Pro 16", 1799.99, "Obsidian black", "Magnesium alloy", "14.1 x 10.0 x 0.7 in", "2.8 lb"),
      product("Framework Laptop 13 DIY Edition", 1049.0, "Silver", "Aluminum, recycled plastic", "11.7 x 9.0 x 0.6 in", "2.9 lb"),
    ],
  },
  {
    id: "cat_phones",
    name: "Phones",
    slug: "phones",
    description: "Flagship and midrange smartphones with strong cameras, batteries, and long software support.",
    featured: true,
    tone: "from-purple-500/20 via-pink-500/10 to-transparent",
    brands: ["Apple", "Samsung", "Google", "OnePlus", "Motorola"],
    tags: ["5g", "camera", "unlocked", "dual-sim"],
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop",
    products: [
      product("Apple iPhone 15 Pro 256GB", 1099.0, "Natural titanium", "Titanium, glass", "5.77 x 2.78 x 0.32 in", "0.41 lb"),
      product("Samsung Galaxy S24 Ultra 512GB", 1299.99, "Titanium grey", "Titanium, Gorilla Armor", "6.4 x 3.1 x 0.3 in", "0.51 lb"),
      product("Google Pixel 8 Pro 256GB", 999.0, "Bay blue", "Aluminum, glass", "6.4 x 3.0 x 0.3 in", "0.47 lb"),
      product("OnePlus 12 16GB 512GB", 899.99, "Flowy emerald", "Aluminum, glass", "6.5 x 3.0 x 0.4 in", "0.49 lb"),
      product("Motorola Razr Plus 2024", 999.99, "Peach fuzz", "Aluminum, vegan leather", "6.7 in unfolded", "0.42 lb"),
      product("Samsung Galaxy Z Flip5 256GB", 999.99, "Mint", "Armor aluminum, glass", "6.5 x 2.8 x 0.3 in", "0.41 lb"),
      product("Apple iPhone 15 128GB", 799.0, "Blue", "Aluminum, color-infused glass", "5.8 x 2.8 x 0.3 in", "0.38 lb"),
      product("Google Pixel 8a 128GB", 499.0, "Aloe", "Aluminum, composite back", "6.0 x 2.9 x 0.4 in", "0.41 lb"),
      product("Nothing Phone 2 256GB", 699.0, "White", "Aluminum, transparent glass", "6.4 x 3.0 x 0.3 in", "0.44 lb"),
      product("ASUS ROG Phone 8 Pro", 1199.99, "Phantom black", "Aluminum, Gorilla Glass", "6.4 x 3.0 x 0.4 in", "0.50 lb"),
    ],
  },
  {
    id: "cat_cameras",
    name: "Cameras",
    slug: "cameras",
    description: "Mirrorless bodies, action cams, instant cameras, and creator-ready photo accessories.",
    featured: false,
    tone: "from-red-500/20 via-orange-500/10 to-transparent",
    brands: ["Canon", "Sony", "Fujifilm", "GoPro", "Nikon"],
    tags: ["creator", "mirrorless", "video", "travel"],
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=600&fit=crop",
    products: [
      product("Sony Alpha a6700 Mirrorless Body", 1398.0, "Black", "Magnesium alloy", "4.8 x 2.7 x 2.5 in", "1.1 lb"),
      product("Canon EOS R8 Mirrorless Camera", 1499.0, "Black", "Magnesium, polycarbonate", "5.2 x 3.4 x 2.8 in", "1.0 lb"),
      product("Fujifilm X-T5 Silver Body", 1699.0, "Silver black", "Magnesium alloy", "5.1 x 3.6 x 2.5 in", "1.2 lb"),
      product("GoPro HERO12 Black Action Camera", 399.99, "Black", "Rugged polymer", "2.8 x 2.0 x 1.3 in", "0.34 lb"),
      product("Nikon Z fc 16-50mm Kit", 1099.95, "Silver", "Magnesium alloy", "5.3 x 3.7 x 1.8 in", "1.0 lb"),
      product("DJI Osmo Action 4 Adventure Combo", 499.0, "Black", "Polycarbonate", "2.8 x 1.7 x 1.3 in", "0.32 lb"),
      product("Insta360 X4 8K Camera", 499.99, "Black", "Plastic, glass lenses", "4.9 x 1.8 x 1.5 in", "0.45 lb"),
      product("Polaroid Now+ Gen 2 Camera", 149.99, "Forest green", "Recycled plastic", "5.9 x 4.4 x 3.8 in", "1.0 lb"),
      product("Peak Design Capture Camera Clip", 74.95, "Black", "Aluminum", "3.3 x 1.6 x 0.8 in", "0.19 lb"),
      product("Sigma 18-50mm F2.8 DC DN Lens", 549.0, "Black", "Composite, glass", "2.6 x 3.0 in", "0.64 lb"),
    ],
  },
  {
    id: "cat_gaming",
    name: "Gaming",
    slug: "gaming",
    description: "Consoles, controllers, headsets, handhelds, and accessories for modern play.",
    featured: false,
    tone: "from-green-500/20 via-teal-500/10 to-transparent",
    brands: ["Sony", "Microsoft", "Nintendo", "Valve", "SteelSeries"],
    tags: ["console", "controller", "handheld", "rgb"],
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&h=600&fit=crop",
    products: [
      product("PlayStation 5 Slim Disc Console", 499.99, "White black", "Plastic, metal chassis", "14.1 x 8.5 x 3.8 in", "7.1 lb"),
      product("Xbox Series X 1TB Console", 499.99, "Matte black", "Plastic, metal chassis", "11.9 x 5.9 x 5.9 in", "9.8 lb"),
      product("Nintendo Switch OLED Console", 349.99, "White", "Plastic, glass screen", "9.5 x 4.0 x 0.6 in", "0.93 lb"),
      product("Valve Steam Deck OLED 1TB", 649.0, "Black", "Plastic, etched glass", "11.7 x 4.6 x 1.9 in", "1.4 lb"),
      product("Sony DualSense Edge Controller", 199.99, "White black", "Plastic, rubber grips", "6.3 x 4.2 x 2.6 in", "0.73 lb"),
      product("Xbox Elite Wireless Controller Series 2", 179.99, "Black", "Plastic, metal paddles", "6.9 x 7.0 x 2.9 in", "0.76 lb"),
      product("SteelSeries Arctis Nova 7 Headset", 179.99, "Black", "Steel, fabric, foam", "7.6 x 3.4 x 7.4 in", "0.71 lb"),
      product("Razer Kishi V2 Mobile Controller", 99.99, "Black", "Polycarbonate", "7.1 x 3.6 x 1.3 in", "0.28 lb"),
      product("Elgato HD60 X Capture Card", 179.99, "Black", "Plastic, metal", "4.4 x 2.8 x 0.7 in", "0.20 lb"),
      product("Backbone One USB-C Controller", 99.99, "Black", "Plastic, rubber", "6.9 x 3.7 x 1.3 in", "0.30 lb"),
    ],
  },
  {
    id: "cat_smart_home",
    name: "Smart Home",
    slug: "smart-home",
    description: "Connected lighting, sensors, cameras, speakers, and automation devices for safer homes.",
    featured: false,
    tone: "from-yellow-500/20 via-lime-500/10 to-transparent",
    brands: ["Google Nest", "Amazon", "Philips Hue", "Eufy", "Ecobee"],
    tags: ["automation", "security", "matter", "energy-saving"],
    image: "https://images.unsplash.com/photo-1558002038-1055907df827?w=600&h=600&fit=crop",
    products: [
      product("Google Nest Hub Max", 229.0, "Chalk", "Fabric, plastic, glass", "9.9 x 7.2 x 4.0 in", "2.9 lb"),
      product("Amazon Echo Show 8 3rd Gen", 149.99, "Charcoal", "Fabric, recycled plastic", "7.9 x 5.5 x 4.2 in", "2.3 lb"),
      product("Philips Hue White Color Starter Kit", 199.99, "White", "Glass, plastic", "A19 bulbs", "1.5 lb"),
      product("EufyCam 3 Security Kit 2-Cam", 549.99, "White", "Weatherproof plastic", "2.6 x 2.6 x 5.1 in", "3.8 lb"),
      product("Ecobee Smart Thermostat Premium", 249.99, "Black", "Glass, zinc, plastic", "4.1 x 4.1 x 1.0 in", "1.3 lb"),
      product("Aqara Door Window Sensor P2", 29.99, "White", "Plastic", "3.0 x 0.9 x 0.3 in", "0.08 lb"),
      product("Lutron Caseta Smart Dimmer Kit", 99.95, "White", "Plastic", "2.9 x 4.7 x 1.5 in", "0.40 lb"),
      product("TP-Link Kasa Smart Plug Mini 4-Pack", 29.99, "White", "Plastic", "2.6 x 1.5 x 1.6 in", "0.45 lb"),
      product("Ring Battery Doorbell Plus", 179.99, "Satin nickel", "Plastic, metal faceplate", "5.1 x 2.4 x 1.1 in", "0.54 lb"),
      product("Nanoleaf Shapes Hexagons 9-Pack", 199.99, "White", "Plastic, LED panels", "9 x 7.8 in each", "3.2 lb"),
    ],
  },
  {
    id: "cat_home_office",
    name: "Home Office",
    slug: "home-office",
    description: "Furniture, lighting, organizers, and ergonomic essentials for focused workspaces.",
    featured: false,
    tone: "from-zinc-500/20 via-stone-500/10 to-transparent",
    brands: ["Herman Miller", "Fully", "Grovemade", "IKEA", "Uplift"],
    tags: ["ergonomic", "organization", "lighting", "workspace"],
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=600&h=600&fit=crop",
    products: [
      product("Herman Miller Sayl Task Chair", 735.0, "Slate grey", "Elastomer, steel", "24.5 x 26 x 40.75 in", "37 lb"),
      product("Fully Jarvis Bamboo Standing Desk", 699.0, "Bamboo black", "Bamboo, steel frame", "48 x 30 x 29 in", "96 lb"),
      product("Grovemade Wood Desk Shelf Large", 280.0, "Walnut", "Walnut, cork, aluminum", "31.5 x 9.0 x 4.2 in", "7.0 lb"),
      product("BenQ e-Reading Desk Lamp", 229.0, "Silver", "Aluminum, zinc alloy", "23.2 x 8.7 x 24.6 in", "8.6 lb"),
      product("Uplift Motion-X Balance Board", 99.0, "Black", "Wood, soft-touch top", "26 x 12.2 x 2.8 in", "7.5 lb"),
      product("Twelve South HiRise Pro Stand", 99.99, "Gunmetal", "Aluminum, vegan leather", "8.5 x 8.9 x 4.4 in", "1.7 lb"),
      product("IKEA Skadis Pegboard Organizer Kit", 39.99, "White", "Fiberboard, steel", "22 x 22 in", "3.1 lb"),
      product("Ergotron LX Monitor Arm", 209.0, "Polished aluminum", "Aluminum", "Single monitor arm", "8.4 lb"),
      product("Fellowes Microban Foot Rest", 29.99, "Black", "Plastic", "18 x 13 x 4.5 in", "3.4 lb"),
      product("Yamazaki Tower Cable Box", 44.0, "White", "ABS resin", "15.7 x 6.1 x 5.7 in", "2.2 lb"),
    ],
  },
  {
    id: "cat_kitchen",
    name: "Kitchen",
    slug: "kitchen",
    description: "Countertop appliances, prep tools, cookware, and coffee gear for everyday cooking.",
    featured: false,
    tone: "from-red-500/20 via-rose-500/10 to-transparent",
    brands: ["Breville", "Ninja", "KitchenAid", "OXO", "Le Creuset"],
    tags: ["appliance", "cookware", "coffee", "meal-prep"],
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=600&h=600&fit=crop",
    products: [
      product("Breville Barista Express Espresso Machine", 699.95, "Brushed stainless", "Stainless steel", "12.5 x 12.6 x 13.1 in", "23 lb"),
      product("Ninja Foodi DualZone Air Fryer", 199.99, "Grey", "Plastic, nonstick baskets", "15.6 x 13.9 x 12.8 in", "17.9 lb"),
      product("KitchenAid Artisan Stand Mixer 5qt", 449.99, "Empire red", "Zinc, stainless bowl", "14.1 x 8.7 x 13.9 in", "22 lb"),
      product("OXO Good Grips POP Container Set", 54.99, "White clear", "BPA-free plastic", "10-piece set", "4.2 lb"),
      product("Le Creuset Signature Dutch Oven 5.5qt", 419.95, "Cerise", "Enameled cast iron", "12.9 x 10.3 x 6.8 in", "11.4 lb"),
      product("Zwilling Pro Chef Knife 8in", 159.99, "Steel black", "German steel, polymer handle", "8 in blade", "0.55 lb"),
      product("Fellow Stagg EKG Electric Kettle", 165.0, "Matte black", "Stainless steel", "11.5 x 6.75 x 8 in", "2.75 lb"),
      product("Vitamix Explorian E310 Blender", 349.95, "Black", "Tritan, stainless blades", "11 x 8 x 18 in", "10.5 lb"),
      product("Instant Pot Duo Plus 6qt", 129.99, "Stainless black", "Stainless steel, plastic", "13.4 x 12.2 x 12.5 in", "12.4 lb"),
      product("Staub Ceramic Baking Dish Set", 99.99, "Dark blue", "Glazed ceramic", "3-piece set", "8.0 lb"),
    ],
  },
  {
    id: "cat_beauty",
    name: "Beauty",
    slug: "beauty",
    description: "Skincare, styling tools, grooming devices, and clean beauty staples.",
    featured: false,
    tone: "from-pink-500/20 via-fuchsia-500/10 to-transparent",
    brands: ["Dyson", "Drunk Elephant", "Olaplex", "Therabody", "Supergoop"],
    tags: ["skincare", "haircare", "grooming", "self-care"],
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=600&fit=crop",
    products: [
      product("Dyson Airwrap Multi-Styler Complete", 599.99, "Prussian blue", "Polycarbonate, ceramic coating", "10.7 x 1.6 x 1.9 in", "1.5 lb"),
      product("Drunk Elephant Protini Polypeptide Cream", 68.0, "White teal", "Airless jar", "50 ml", "0.3 lb"),
      product("Olaplex No.3 Hair Perfector", 30.0, "White", "Recyclable bottle", "100 ml", "0.35 lb"),
      product("Therabody TheraFace Pro", 399.0, "White", "Silicone, plastic", "6.7 x 2.0 x 1.8 in", "0.48 lb"),
      product("Supergoop Unseen Sunscreen SPF 40", 38.0, "Clear", "Tube packaging", "1.7 oz", "0.15 lb"),
      product("Foreo Luna 4 Facial Cleansing Device", 279.0, "Lavender", "Ultra-hygienic silicone", "3.2 x 3.2 x 1.5 in", "0.28 lb"),
      product("T3 AireLuxe Professional Hair Dryer", 199.99, "Graphite", "Plastic, ceramic heater", "9.5 x 3.3 x 10.4 in", "1.3 lb"),
      product("Kiehl's Ultra Facial Cream 125ml", 67.0, "White", "Recyclable jar", "125 ml", "0.55 lb"),
      product("Braun Series 9 Pro+ Electric Shaver", 329.99, "Graphite", "Metal, rubber grip", "6.6 x 2.5 x 2.5 in", "0.46 lb"),
      product("Laneige Lip Sleeping Mask Berry", 24.0, "Pink", "Glass jar", "20 g", "0.16 lb"),
    ],
  },
  {
    id: "cat_fashion",
    name: "Fashion",
    slug: "fashion",
    description: "Everyday apparel, outerwear, bags, and accessories with reliable materials and sizing.",
    featured: false,
    tone: "from-neutral-500/20 via-slate-500/10 to-transparent",
    brands: ["Patagonia", "Levi's", "Nike", "Everlane", "Uniqlo"],
    tags: ["apparel", "outerwear", "essentials", "travel"],
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&h=600&fit=crop",
    products: [
      product("Patagonia Nano Puff Jacket", 239.0, "Forge grey", "Recycled polyester", "Regular fit", "0.75 lb"),
      product("Levi's 501 Original Fit Jeans", 89.5, "Medium indigo", "Cotton denim", "Waist 28-40", "1.4 lb"),
      product("Nike Tech Fleece Hoodie", 125.0, "Light bone", "Cotton polyester fleece", "XS-XXL", "1.1 lb"),
      product("Everlane Organic Cotton Box-Cut Tee", 30.0, "Black", "Organic cotton", "XS-XL", "0.35 lb"),
      product("Uniqlo Ultra Light Down Vest", 59.9, "Olive", "Nylon, down fill", "XS-XXL", "0.40 lb"),
      product("Allbirds Wool Runner 2", 110.0, "Natural grey", "Merino wool, bio-based sole", "Men 8-13", "1.2 lb"),
      product("Madewell Transport Tote", 178.0, "English saddle", "Leather", "14 x 14.25 x 6.25 in", "1.9 lb"),
      product("Carhartt Knit Cuffed Beanie", 19.99, "Carhartt brown", "Acrylic knit", "One size", "0.18 lb"),
      product("Arc'teryx Mantis 2 Waist Pack", 50.0, "Black", "Recycled polyester", "9.5 x 7.5 x 2.5 in", "0.40 lb"),
      product("Bombas Merino Wool Socks 4-Pack", 72.0, "Mixed neutral", "Merino wool blend", "M-L", "0.45 lb"),
    ],
  },
  {
    id: "cat_sports",
    name: "Sports",
    slug: "sports",
    description: "Training gear, recovery tools, hydration, and outdoor equipment for active customers.",
    featured: false,
    tone: "from-lime-500/20 via-green-500/10 to-transparent",
    brands: ["Nike", "Adidas", "Hydro Flask", "Therabody", "Yeti"],
    tags: ["training", "outdoor", "hydration", "recovery"],
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=600&fit=crop",
    products: [
      product("Nike Metcon 9 Training Shoes", 150.0, "Black white", "Mesh, rubber sole", "Men 7-13", "1.6 lb"),
      product("Adidas Ultraboost Light Running Shoes", 190.0, "Cloud white", "Primeknit, Boost foam", "Women 5-11", "1.4 lb"),
      product("Hydro Flask Wide Mouth 32oz", 44.95, "Agave", "Stainless steel", "32 oz", "1.0 lb"),
      product("Therabody Wave Roller", 149.0, "Black", "Hypoallergenic foam", "12 x 5.1 in", "3.3 lb"),
      product("Yeti Hopper Flip 12 Soft Cooler", 250.0, "Navy", "DryHide shell", "12.6 x 10 x 11.5 in", "3.1 lb"),
      product("Manduka Pro Yoga Mat 6mm", 138.0, "Black sage", "PVC closed-cell", "71 x 26 x 0.24 in", "7.5 lb"),
      product("TRX All-in-One Suspension Trainer", 169.95, "Black yellow", "Nylon webbing, rubber handles", "Adjustable", "1.7 lb"),
      product("Garmin HRM-Pro Plus Strap", 129.99, "Black", "Textile strap, sensor", "Adjustable", "0.12 lb"),
      product("Hyperice Normatec Lower Legs", 399.0, "Black", "Nylon, compression chambers", "Pair", "3.4 lb"),
      product("Osprey Daylite Plus Backpack", 75.0, "Wave blue", "Recycled nylon", "18.9 x 11 x 9.5 in", "1.3 lb"),
    ],
  },
  {
    id: "cat_toys",
    name: "Toys",
    slug: "toys",
    description: "STEM kits, building sets, plush, puzzles, and family games for different age ranges.",
    featured: false,
    tone: "from-cyan-500/20 via-blue-500/10 to-transparent",
    brands: ["LEGO", "Hasbro", "Mattel", "Ravensburger", "KiwiCo"],
    tags: ["kids", "stem", "family", "gifts"],
    image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&h=600&fit=crop",
    products: [
      product("LEGO Icons Bonsai Tree Set", 49.99, "Green brown", "ABS plastic", "8 x 7 x 7 in", "1.4 lb"),
      product("KiwiCo Tinker Crate Robotics Kit", 34.95, "Multi", "Wood, electronics", "9 x 6 x 2 in", "1.0 lb"),
      product("Ravensburger 1000 Piece World Map Puzzle", 24.99, "Multi", "Cardboard", "27 x 20 in", "1.6 lb"),
      product("Hasbro Clue Classic Board Game", 21.99, "Multi", "Cardboard, plastic", "15.8 x 10.5 x 2 in", "1.8 lb"),
      product("Mattel Barbie Dream Camper", 89.99, "Pink blue", "Plastic", "23 x 9 x 12 in", "7.1 lb"),
      product("Magna-Tiles Clear Colors 100-Piece Set", 119.99, "Multi", "ABS plastic, magnets", "100 pieces", "6.0 lb"),
      product("Osmo Genius Starter Kit", 99.99, "White red", "Plastic, cardboard", "iPad compatible", "2.0 lb"),
      product("Jellycat Bashful Bunny Medium", 32.5, "Cream", "Polyester plush", "12 in", "0.30 lb"),
      product("Hot Wheels Track Builder Unlimited Box", 49.99, "Orange blue", "Plastic", "20 x 12 x 6 in", "4.5 lb"),
      product("Nintendo Super Mario LEGO Starter Course", 59.99, "Multi", "ABS plastic", "231 pieces", "1.2 lb"),
    ],
  },
  {
    id: "cat_baby",
    name: "Baby",
    slug: "baby",
    description: "Nursery gear, feeding tools, safety essentials, and parent-tested everyday baby products.",
    featured: false,
    tone: "from-teal-500/20 via-cyan-500/10 to-transparent",
    brands: ["Nuna", "Uppababy", "BabyBjorn", "Frida", "Hatch"],
    tags: ["nursery", "feeding", "safety", "new-parent"],
    image: "https://images.unsplash.com/photo-1519689680058-324335c77eba?w=600&h=600&fit=crop",
    products: [
      product("Nuna Pipa RX Infant Car Seat", 550.0, "Caviar", "Merino wool, aluminum", "26.6 x 17.5 x 22.5 in", "7.6 lb"),
      product("Uppababy Vista V2 Stroller", 999.99, "Greyson charcoal", "Aluminum, polyester", "36 x 25.7 x 39.5 in", "27 lb"),
      product("BabyBjorn Bouncer Bliss", 209.99, "Light grey", "Cotton, steel frame", "31 x 15.5 x 22 in", "4.6 lb"),
      product("Frida Baby Electric NoseFrida", 44.99, "White blue", "Plastic, silicone tips", "6.3 x 2.1 x 2.1 in", "0.40 lb"),
      product("Hatch Rest Go Portable Sound Machine", 34.99, "Mint", "Plastic, silicone loop", "3.5 x 3.5 x 1.5 in", "0.33 lb"),
      product("Boon Lawn Countertop Drying Rack", 29.99, "Green white", "BPA-free plastic", "13.5 x 11 x 2.5 in", "1.5 lb"),
      product("Lovevery Play Gym", 140.0, "Natural", "FSC wood, organic cotton", "43 x 38 x 24 in", "7.0 lb"),
      product("Skip Hop Forma Diaper Backpack", 79.99, "Black", "Polyester", "16 x 8 x 14 in", "1.8 lb"),
      product("Munchkin 59S Mini Sterilizer", 29.99, "White", "Plastic, UV-C LED", "3.2 x 3.2 x 3.9 in", "0.40 lb"),
      product("Nanobebe Flexy Silicone Bottle 3-Pack", 29.99, "Teal", "Silicone", "8 oz each", "0.8 lb"),
    ],
  },
  {
    id: "cat_pets",
    name: "Pets",
    slug: "pets",
    description: "Smart feeders, beds, grooming, toys, and travel accessories for cats and dogs.",
    featured: false,
    tone: "from-orange-500/20 via-yellow-500/10 to-transparent",
    brands: ["Furbo", "PetSafe", "Kong", "Ruffwear", "Whisker"],
    tags: ["dog", "cat", "smart-pet", "travel"],
    image: "https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=600&h=600&fit=crop",
    products: [
      product("Furbo 360 Dog Camera", 199.0, "White bamboo", "Plastic, bamboo lid", "5.9 x 4.9 x 8.8 in", "2.1 lb"),
      product("PetSafe Smart Feed Automatic Feeder", 169.95, "White", "Plastic, stainless bowl", "19 x 9 x 13 in", "5.0 lb"),
      product("Kong Classic Dog Toy Large", 14.99, "Red", "Natural rubber", "4 x 2.8 in", "0.45 lb"),
      product("Ruffwear Front Range Dog Harness", 49.95, "Blue dusk", "Nylon, foam padding", "M", "0.40 lb"),
      product("Whisker Litter-Robot 4", 699.0, "Black", "Plastic, carbon filter", "22 x 27 x 29.5 in", "24 lb"),
      product("Sleepypod Air Pet Carrier", 189.99, "Dark chocolate", "Nylon, mesh", "22 x 10.5 x 10.5 in", "4.5 lb"),
      product("Fable Pets Game Toy", 55.0, "Spruce", "Natural rubber", "5.5 x 5.5 x 5.5 in", "1.0 lb"),
      product("Catit Flower Fountain 3L", 32.99, "White green", "Plastic", "8.7 x 8.7 x 7.7 in", "1.6 lb"),
      product("Bissell BarkBath Dual Use Cleaner", 199.99, "Grapevine purple", "Plastic", "10 x 14 x 14 in", "9.0 lb"),
      product("Wild One Everyday Carrier", 125.0, "Tan", "Polyester, mesh", "17.5 x 11 x 10 in", "2.7 lb"),
    ],
  },
  {
    id: "cat_automotive",
    name: "Automotive",
    slug: "automotive",
    description: "Car care, chargers, dash cams, organizers, and emergency essentials for daily drivers.",
    featured: false,
    tone: "from-stone-500/20 via-neutral-500/10 to-transparent",
    brands: ["Garmin", "Anker", "Chemical Guys", "NOCO", "WeatherTech"],
    tags: ["car-care", "travel", "charging", "safety"],
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600&h=600&fit=crop",
    products: [
      product("Garmin Dash Cam Mini 2", 129.99, "Black", "Plastic, glass lens", "1.2 x 2.1 x 1.1 in", "0.07 lb"),
      product("Anker Roav SmartCharge F3", 29.99, "Black", "Plastic, metal contacts", "3.6 x 1.9 x 1.9 in", "0.12 lb"),
      product("Chemical Guys Starter Car Wash Kit", 59.99, "Multi", "Microfiber, liquid cleaners", "7-piece kit", "6.5 lb"),
      product("NOCO Boost Plus GB40 Jump Starter", 99.95, "Black orange", "Plastic, lithium battery", "7.7 x 3.2 x 1.7 in", "2.4 lb"),
      product("WeatherTech FloorLiner Set", 229.95, "Black", "Thermoplastic elastomer", "Vehicle-specific", "8.0 lb"),
      product("Carhartt Seat Organizer", 39.99, "Brown", "Polyester duck fabric", "15 x 24 in", "1.3 lb"),
      product("iOttie Easy One Touch 5 Mount", 24.95, "Black", "Plastic, suction cup", "4.3 x 4.1 x 6.6 in", "0.42 lb"),
      product("Armor All Portable Wet/Dry Vacuum", 59.99, "Orange black", "Plastic", "10.6 x 14.2 x 14.4 in", "7.0 lb"),
      product("Tesla J1772 Wall Connector Adapter", 99.0, "Black", "Plastic, copper contacts", "6.5 x 2.5 x 2.5 in", "0.70 lb"),
      product("Yakima HighRoad Bike Rack", 299.0, "Black", "Aluminum, steel", "56 x 9.5 x 4.5 in", "18 lb"),
    ],
  },
  {
    id: "cat_books",
    name: "Books",
    slug: "books",
    description: "Business, design, fiction, cooking, and practical reference books for curious shoppers.",
    featured: false,
    tone: "from-indigo-500/20 via-blue-500/10 to-transparent",
    brands: ["Penguin", "O'Reilly", "Phaidon", "Ten Speed", "HarperCollins"],
    tags: ["reading", "learning", "gift", "reference"],
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=600&fit=crop",
    products: [
      product("Atomic Habits Hardcover", 27.0, "Navy", "Paper, cloth cover", "6.3 x 1.1 x 9.3 in", "1.1 lb"),
      product("Designing Data-Intensive Applications", 54.99, "Blue", "Paperback", "7 x 1.6 x 9.2 in", "2.5 lb"),
      product("The Creative Act by Rick Rubin", 32.0, "White", "Hardcover", "6 x 1.2 x 8.6 in", "1.3 lb"),
      product("Salt Fat Acid Heat Cookbook", 37.5, "Illustrated", "Hardcover", "8.3 x 1.3 x 10.3 in", "3.2 lb"),
      product("Dune Deluxe Edition", 50.0, "Sand", "Hardcover, sprayed edges", "6.3 x 1.8 x 9.3 in", "2.2 lb"),
      product("The Art of Pixar Boxed Postcard Set", 22.95, "Multi", "Cardstock", "100 postcards", "1.7 lb"),
      product("O'Reilly JavaScript Definitive Guide", 59.99, "Rhino white", "Paperback", "7 x 1.6 x 9.2 in", "2.8 lb"),
      product("Monocle Guide to Better Living", 65.0, "Yellow", "Hardcover", "8 x 1.2 x 10.5 in", "3.0 lb"),
      product("The Psychology of Money", 19.99, "Black gold", "Paperback", "5.5 x 0.6 x 8.4 in", "0.55 lb"),
      product("Phaidon Where Chefs Eat", 35.0, "Orange", "Paperback", "5.4 x 1.7 x 8.1 in", "1.5 lb"),
    ],
  },
  {
    id: "cat_grocery",
    name: "Grocery",
    slug: "grocery",
    description: "Pantry staples, specialty coffee, snacks, sauces, and better-for-you everyday groceries.",
    featured: false,
    tone: "from-emerald-500/20 via-yellow-500/10 to-transparent",
    brands: ["Blue Bottle", "Graza", "Fly By Jing", "Maldon", "Hu"],
    tags: ["pantry", "coffee", "snacks", "organic"],
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&h=600&fit=crop",
    products: [
      product("Blue Bottle Bella Donovan Coffee 12oz", 17.0, "Blue bag", "Whole bean coffee", "12 oz", "0.85 lb"),
      product("Graza Sizzle Extra Virgin Olive Oil", 15.0, "Green bottle", "PET squeeze bottle", "16.9 oz", "1.1 lb"),
      product("Fly By Jing Sichuan Chili Crisp", 15.0, "Red jar", "Glass jar", "6 oz", "0.70 lb"),
      product("Maldon Sea Salt Flakes 8.5oz", 8.99, "White box", "Cardboard box", "8.5 oz", "0.65 lb"),
      product("Hu Simple Dark Chocolate 4-Pack", 22.0, "Brown", "Wrapped bars", "4 x 2.1 oz", "0.65 lb"),
      product("Omsom Saucy Noodle Variety Pack", 39.0, "Multi", "Shelf-stable packets", "8 meals", "2.4 lb"),
      product("Banza Chickpea Pasta Variety Pack", 27.99, "Orange boxes", "Cardboard boxes", "6 x 8 oz", "3.6 lb"),
      product("Partake Gluten-Free Cookie Bundle", 24.99, "Multi", "Resealable bags", "3 bags", "1.2 lb"),
      product("Kettle & Fire Bone Broth 6-Pack", 47.94, "Mixed cartons", "Carton packaging", "6 x 16.9 oz", "7.2 lb"),
      product("Minor Figures Oat Milk Barista 6-Pack", 29.99, "White cartons", "Shelf-stable cartons", "6 x 32 oz", "13.0 lb"),
    ],
  },
  {
    id: "cat_health",
    name: "Health",
    slug: "health",
    description: "Wellness devices, supplements, first-aid, hydration, and recovery products for daily care.",
    featured: false,
    tone: "from-green-500/20 via-cyan-500/10 to-transparent",
    brands: ["Withings", "Omron", "Liquid I.V.", "Nature Made", "First Aid Only"],
    tags: ["wellness", "monitoring", "supplements", "recovery"],
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&h=600&fit=crop",
    products: [
      product("Withings Body Smart Scale", 99.95, "Black", "Tempered glass", "12.8 x 12.8 x 0.9 in", "4.4 lb"),
      product("Omron Platinum Blood Pressure Monitor", 84.99, "White black", "Plastic, nylon cuff", "7.5 x 4.7 x 3.3 in", "1.6 lb"),
      product("Liquid I.V. Hydration Multiplier 24-Pack", 36.99, "Lemon lime", "Powder packets", "24 sticks", "1.1 lb"),
      product("Nature Made Vitamin D3 2000 IU", 12.99, "Yellow", "Bottle", "220 softgels", "0.25 lb"),
      product("First Aid Only 299-Piece Kit", 24.99, "White", "Plastic case", "9.3 x 7.3 x 2.9 in", "1.4 lb"),
      product("Theragun Mini 2.0", 199.0, "Black", "Plastic, soft grip", "5.6 x 4.9 x 1.9 in", "1.0 lb"),
      product("S'well Stainless Bottle 25oz", 35.0, "Teakwood", "Stainless steel", "25 oz", "0.90 lb"),
      product("Philips Sonicare 4100 Toothbrush", 49.99, "White", "Plastic", "9.6 x 2.5 x 4.3 in", "0.70 lb"),
      product("Homedics TotalClean Air Purifier", 129.99, "White", "Plastic, HEPA filter", "9 x 9 x 20 in", "8.8 lb"),
      product("Aura Carver Digital Photo Frame", 149.0, "Charcoal", "Plastic, glass", "10.1 in display", "1.5 lb"),
    ],
  },
  {
    id: "cat_outdoor",
    name: "Outdoor",
    slug: "outdoor",
    description: "Camping, hiking, travel, and weather-ready gear built for weekends outside.",
    featured: false,
    tone: "from-lime-500/20 via-emerald-500/10 to-transparent",
    brands: ["Patagonia", "REI Co-op", "Yeti", "BioLite", "Black Diamond"],
    tags: ["camping", "hiking", "travel", "weatherproof"],
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600&h=600&fit=crop",
    products: [
      product("REI Co-op Half Dome SL 2+ Tent", 349.0, "Blue grey", "Ripstop nylon, aluminum poles", "88 x 56 x 42 in", "4.9 lb"),
      product("Yeti Rambler 20oz Tumbler", 35.0, "Seafoam", "Stainless steel", "20 oz", "0.80 lb"),
      product("BioLite CampStove 2+", 149.95, "Orange", "Stainless steel, battery pack", "5 x 5 x 8.3 in", "2.1 lb"),
      product("Black Diamond Spot 400 Headlamp", 49.95, "Graphite", "Plastic, elastic strap", "One size", "0.19 lb"),
      product("Patagonia Black Hole Duffel 55L", 169.0, "Smolder blue", "Recycled ripstop polyester", "26.7 x 15.7 x 11.8 in", "2.6 lb"),
      product("Jetboil Flash Cooking System", 129.95, "Carbon", "Aluminum, stainless steel", "4.1 x 7.1 in", "0.82 lb"),
      product("Hydro Flask Trail Series 24oz", 39.95, "Slate", "Stainless steel", "24 oz", "0.69 lb"),
      product("Rumpl Original Puffy Blanket", 125.0, "Deepwater", "Recycled polyester", "52 x 75 in", "2.1 lb"),
      product("Garmin inReach Mini 2", 399.99, "Flame red", "Impact-resistant plastic", "2.0 x 3.9 x 1.0 in", "0.22 lb"),
      product("Nemo Tensor All-Season Sleeping Pad", 199.95, "Marigold", "Nylon, TPU film", "72 x 20 x 3.5 in", "1.2 lb"),
    ],
  },
];

export const mockCatalogCategories: MockCatalogCategory[] =
  allMockCatalogCategories.slice(0, 20);
