import { mockCatalogCategories } from "./catalog";
import type { MockProduct } from "./types";

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/['.]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const stockLevels = [18, 8, 24, 12, 36, 5, 62, 14, 0, 47];
const statuses: Array<NonNullable<MockProduct["status"]>> = [
  "active",
  "active",
  "active",
  "active",
  "draft",
  "active",
  "active",
  "active",
  "archived",
  "active",
];


export const mockProducts: MockProduct[] = [
  {
    id: "prod_001",
    name: "iPhone 15 Pro Max",
    sku: "APL-IP15PM-256-BLK",
    price: 1199,
    currency: "USD",
    brand: "Apple",
    categoryId: "cat_001",
    categorySlug: "smartphones",
    categoryName: "Smartphones",
    compareAtPrice: 1299,
    cost: 780,
    rating: 4.8,
    reviewCount: 312,
    stock: 45,
    status: "active",
    tags: ["flagship", "5g", "pro"],
    color: "Black Titanium",
    material: "Titanium",
    warranty: "1 year",
    releaseDate: "2023-09-22",
    weight: "221g",
    dimensions: "159.9 × 76.7 × 8.25 mm",
    description:
      "The most powerful iPhone ever with the A17 Pro chip, titanium design, and USB-C.",
  },
  {
    id: "prod_002",
    name: "Samsung Galaxy S24 Ultra",
    sku: "SAM-GS24U-512-TIT",
    price: 899,
    currency: "USD",
    brand: "Samsung",
    categoryId: "cat_001",
    categorySlug: "smartphones",
    categoryName: "Smartphones",
    compareAtPrice: 999,
    cost: 560,
    rating: 4.6,
    reviewCount: 245,
    stock: 38,
    status: "active",
    tags: ["flagship", "s-pen", "200mp"],
    color: "Titanium Gray",
    material: "Titanium",
    warranty: "1 year",
    releaseDate: "2024-01-17",
    weight: "232g",
    dimensions: "162.3 × 79 × 8.6 mm",
    description: "Built-in S Pen, 200MP camera, and Snapdragon 8 Gen 3.",
  },
  {
    id: "prod_003",
    name: "MacBook Air M3",
    sku: "APL-MBA-M3-16-SLV",
    price: 1299,
    currency: "USD",
    brand: "Apple",
    categoryId: "cat_002",
    categorySlug: "laptops",
    categoryName: "Laptops",
    compareAtPrice: 1399,
    cost: 860,
    rating: 4.9,
    reviewCount: 198,
    stock: 22,
    status: "active",
    tags: ["ultrabook", "m3", "fanless"],
    color: "Silver",
    material: "Aluminium",
    warranty: "1 year",
    releaseDate: "2024-03-08",
    weight: "1.24kg",
    dimensions: "304.1 × 215 × 11.5 mm",
    description:
      "Supercharged by M3 chip with up to 18 hours battery life.",
  },
  {
    id: "prod_004",
    name: "AirPods Pro 2",
    sku: "APL-APP2-USB-WHT",
    price: 249,
    currency: "USD",
    brand: "Apple",
    categoryId: "cat_003",
    categorySlug: "audio",
    categoryName: "Audio",
    compareAtPrice: 279,
    cost: 128,
    rating: 4.7,
    reviewCount: 289,
    stock: 8,
    status: "active",
    tags: ["anc", "wireless", "h2-chip"],
    color: "White",
    material: "Plastic",
    warranty: "1 year",
    releaseDate: "2022-09-23",
    weight: "5.3g",
    dimensions: "30.9 × 21.8 × 24 mm",
    description:
      "Best-in-class Active Noise Cancellation with Adaptive Audio.",
  },
  {
    id: "prod_005",
    name: "Sony WH-1000XM5",
    sku: "SNY-WH1K5-BLK",
    price: 349,
    currency: "USD",
    brand: "Sony",
    categoryId: "cat_003",
    categorySlug: "audio",
    categoryName: "Audio",
    compareAtPrice: 399,
    cost: 195,
    rating: 4.8,
    reviewCount: 187,
    stock: 29,
    status: "active",
    tags: ["anc", "over-ear", "30hr"],
    color: "Midnight Black",
    material: "Plastic/Fabric",
    warranty: "1 year",
    releaseDate: "2022-05-12",
    weight: "250g",
    dimensions: "254 × 187 × 78 mm",
    description:
      "Industry-leading noise cancellation with 30-hour battery.",
  },
  {
    id: "prod_006",
    name: "iPad Air 5",
    sku: "APL-IPA5-256-BLU",
    price: 599,
    currency: "USD",
    brand: "Apple",
    categoryId: "cat_004",
    categorySlug: "tablets",
    categoryName: "Tablets",
    compareAtPrice: 649,
    cost: 380,
    rating: 4.6,
    reviewCount: 163,
    stock: 17,
    status: "active",
    tags: ["m1", "5g", "liquid-retina"],
    color: "Blue",
    material: "Aluminium",
    warranty: "1 year",
    releaseDate: "2022-03-18",
    weight: "461g",
    dimensions: "247.6 × 178.5 × 6.1 mm",
    description: "Powerful M1 chip in a thin and light design.",
  },
  {
    id: "prod_007",
    name: "Logitech MX Master 3S",
    sku: "LGT-MXM3S-GRY",
    price: 99,
    currency: "USD",
    brand: "Logitech",
    categoryId: "cat_005",
    categorySlug: "peripherals",
    categoryName: "Peripherals",
    compareAtPrice: 119,
    cost: 44,
    rating: 4.7,
    reviewCount: 421,
    stock: 63,
    status: "active",
    tags: ["ergonomic", "8k-dpi", "usb-c"],
    color: "Graphite",
    material: "Plastic/Rubber",
    warranty: "2 years",
    releaseDate: "2022-06-02",
    weight: "141g",
    dimensions: "124.9 × 84.3 × 51 mm",
    description: "Advanced performance mouse with near-silent clicks.",
  },
  {
    id: "prod_008",
    name: "Dell XPS 15",
    sku: "DEL-XPS15-RTX-SLV",
    price: 1499,
    currency: "USD",
    brand: "Dell",
    categoryId: "cat_002",
    categorySlug: "laptops",
    categoryName: "Laptops",
    compareAtPrice: 1699,
    cost: 980,
    rating: 4.5,
    reviewCount: 94,
    stock: 11,
    status: "active",
    tags: ["oled", "rtx4060", "creator"],
    color: "Platinum Silver",
    material: "Aluminium/Carbon Fibre",
    warranty: "1 year",
    releaseDate: "2023-11-01",
    weight: "1.86kg",
    dimensions: "344.4 × 230.1 × 18 mm",
    description:
      "OLED touch display with RTX 4060 for creators and professionals.",
  },
  {
    id: "prod_009",
    name: "Nintendo Switch OLED",
    sku: "NIN-SWOL-WHT",
    price: 349,
    currency: "USD",
    brand: "Nintendo",
    categoryId: "cat_006",
    categorySlug: "gaming",
    categoryName: "Gaming",
    compareAtPrice: 369,
    cost: 210,
    rating: 4.7,
    reviewCount: 534,
    stock: 55,
    status: "active",
    tags: ["portable", "oled", "handheld"],
    color: "White",
    material: "Plastic",
    warranty: "1 year",
    releaseDate: "2021-10-08",
    weight: "320g",
    dimensions: "242 × 102 × 13.9 mm",
    description: "Vivid OLED screen with enhanced audio for gaming anywhere.",
  },
  {
    id: "prod_010",
    name: "GoPro Hero 12",
    sku: "GPR-H12-BLK",
    price: 399,
    currency: "USD",
    brand: "GoPro",
    categoryId: "cat_007",
    categorySlug: "cameras",
    categoryName: "Cameras",
    compareAtPrice: 449,
    cost: 228,
    rating: 4.5,
    reviewCount: 211,
    stock: 0,
    status: "active",
    tags: ["4k", "waterproof", "hypersmooth"],
    color: "Black",
    material: "Polycarbonate",
    warranty: "1 year",
    releaseDate: "2023-09-13",
    weight: "154g",
    dimensions: "71.8 × 50.8 × 33.6 mm",
    description: "5.3K video, HyperSmooth 6.0, and longest battery life yet.",
  },
  {
    id: "prod_011",
    name: "Keychron K2 Pro",
    sku: "KEY-K2PRO-RGB-BRN",
    price: 89,
    currency: "USD",
    brand: "Keychron",
    categoryId: "cat_005",
    categorySlug: "peripherals",
    categoryName: "Peripherals",
    compareAtPrice: 109,
    cost: 42,
    rating: 4.8,
    reviewCount: 376,
    stock: 48,
    status: "active",
    tags: ["mechanical", "wireless", "qmk"],
    color: "Space Grey",
    material: "Aluminium",
    warranty: "1 year",
    releaseDate: "2022-08-10",
    weight: "810g",
    dimensions: "327 × 124 × 38 mm",
    description: "QMK/VIA wireless mechanical keyboard with RGB backlight.",
  },
  {
    id: "prod_012",
    name: "USB-C Hub 7-in-1",
    sku: "ANK-USBC7-SLV",
    price: 49,
    currency: "USD",
    brand: "Anker",
    categoryId: "cat_005",
    categorySlug: "peripherals",
    categoryName: "Peripherals",
    cost: 18,
    rating: 4.4,
    reviewCount: 892,
    stock: 5,
    status: "draft",
    tags: ["hub", "usb-c", "4k-hdmi"],
    color: "Silver",
    material: "Aluminium",
    warranty: "18 months",
    releaseDate: "2023-05-01",
    weight: "63g",
    dimensions: "112 × 34 × 14 mm",
    description: "7 ports including 4K HDMI, 100W PD, and 3× USB-A.",
  },
];

// Create a Map for slug-based lookups
export const mockProductBySlug = new Map<string, MockProduct>();
mockProducts.forEach((product) => {
  if (product.categorySlug) {
    mockProductBySlug.set(product.categorySlug, product);
  }
  // Also map by a slugified name
  const nameSlug = slugify(product.name);
  mockProductBySlug.set(nameSlug, product);
});